import { StyleSheet } from 'react-native';

export const homepageStyles = StyleSheet.create({
  screen: {
    flex: 1,
  },
  header: {
    minHeight: 58,
    paddingHorizontal: 18,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitle: {
    fontSize: 20,
    lineHeight: 26,
    fontWeight: '700',
  },
  headerButton: {
    width: 40,
    height: 40,
    borderWidth: 1,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerSpacer: {
    width: 40,
    height: 40,
  },
  content: {
    paddingHorizontal: 18,
    paddingTop: 22,
    paddingBottom: 112,
  },
  centered: {
    flex: 1,
    paddingHorizontal: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyMark: {
    width: 64,
    height: 64,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  pageTitle: {
    fontSize: 24,
    lineHeight: 31,
    fontWeight: '700',
    textAlign: 'center',
  },
  pageSubtitle: {
    marginTop: 8,
    maxWidth: 320,
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'center',
  },
  section: {
    paddingVertical: 18,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  sectionTitle: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
  },
  sectionHint: {
    marginTop: 4,
    fontSize: 13,
    lineHeight: 19,
  },
  input: {
    minHeight: 48,
    marginTop: 10,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 13,
    paddingVertical: 11,
    fontSize: 16,
    lineHeight: 22,
  },
  multilineInput: {
    minHeight: 92,
    textAlignVertical: 'top',
  },
  photoGrid: {
    marginTop: 12,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  photoButton: {
    width: '31.5%',
    aspectRatio: 1,
    borderWidth: 2,
    borderRadius: 6,
    overflow: 'hidden',
  },
  photo: {
    width: '100%',
    height: '100%',
  },
  photoOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: 'flex-end',
    justifyContent: 'flex-start',
    padding: 6,
  },
  photoCheck: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadStatus: {
    position: 'absolute',
    left: 4,
    right: 4,
    bottom: 4,
    minHeight: 25,
    borderRadius: 5,
    paddingHorizontal: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  uploadStatusText: {
    flexShrink: 1,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '700',
  },
  actionRow: {
    marginTop: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  commandButton: {
    minHeight: 46,
    borderRadius: 8,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  commandButtonFill: {
    flex: 1,
  },
  commandText: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
  },
  outlineButton: {
    minHeight: 42,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  outlineText: {
    fontSize: 14,
    lineHeight: 19,
    fontWeight: '600',
  },
  errorText: {
    marginTop: 10,
    fontSize: 13,
    lineHeight: 19,
  },
  statusBand: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderLeftWidth: 3,
    borderRadius: 4,
    marginBottom: 14,
  },
  statusText: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
  },
  overviewTitle: {
    fontSize: 28,
    lineHeight: 35,
    fontWeight: '700',
  },
  overviewSummary: {
    marginTop: 8,
    fontSize: 16,
    lineHeight: 24,
  },
  metadataRow: {
    marginTop: 14,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  metadataPill: {
    borderRadius: 6,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  metadataText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
  },
  toolbar: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  themeRow: {
    marginTop: 10,
    flexDirection: 'row',
    borderWidth: 1,
    borderRadius: 8,
    overflow: 'hidden',
  },
  themeButton: {
    flex: 1,
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionSelector: {
    marginTop: 10,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  sectionButton: {
    minHeight: 38,
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionControlRow: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionControlActions: {
    flexDirection: 'row',
    gap: 8,
  },
  smallIconButton: {
    width: 38,
    height: 38,
    borderWidth: 1,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  preview: {
    flex: 1,
  },
  previewError: {
    position: 'absolute',
    left: 18,
    right: 18,
    bottom: 24,
    padding: 12,
    borderRadius: 8,
  },
  historyRow: {
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  historyCopy: {
    flex: 1,
    paddingRight: 12,
  },
  historyTitle: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
  },
  historyMeta: {
    marginTop: 2,
    fontSize: 12,
    lineHeight: 17,
  },
  marginTop10: {
    marginTop: 10,
  },
  marginTop14: {
    marginTop: 14,
  },
  marginTop18: {
    marginTop: 18,
  },
  marginTop22: {
    marginTop: 22,
  },
  whiteText: {
    color: '#ffffff',
  },
});
