import { StyleSheet } from 'react-native';

export const avatar3dCreateStyles = StyleSheet.create({
  screen: { flex: 1 },
  bodyScroll: { flex: 1 },
  header: {
    alignItems: 'center',
    borderBottomWidth: 2,
    flexDirection: 'row',
    height: 56,
    paddingHorizontal: 12,
  },
  headerButton: {
    alignItems: 'center',
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  backIcon: { height: 22, width: 22 },
  headerTitle: {
    flex: 1,
    fontSize: 17,
    fontWeight: '700',
    textAlign: 'center',
  },
  composerContent: { paddingBottom: 12 },
  section: {
    borderBottomWidth: 2,
    gap: 12,
    paddingHorizontal: 18,
    paddingVertical: 18,
  },
  sectionTitle: { fontSize: 16, fontWeight: '700' },
  photoPicker: {
    aspectRatio: 1.6,
    borderRadius: 8,
    borderWidth: 1,
    overflow: 'hidden',
  },
  photoPreview: { height: '100%', width: '100%' },
  photoPlaceholder: {
    alignItems: 'center',
    flex: 1,
    gap: 7,
    justifyContent: 'center',
    padding: 20,
  },
  photoPickerTitle: { fontSize: 15, fontWeight: '700' },
  photoPickerHint: { fontSize: 12, lineHeight: 18, textAlign: 'center' },
  inlineCommand: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    flexDirection: 'row',
    gap: 6,
    minHeight: 30,
  },
  inlineCommandText: { fontSize: 13, fontWeight: '700' },
  validationResult: {
    alignItems: 'flex-start',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 10,
    padding: 12,
  },
  validationCopy: { flex: 1, gap: 4 },
  validationTitle: { fontSize: 13, fontWeight: '700' },
  validationAdvice: { fontSize: 12, lineHeight: 18 },
  optionRow: { flexDirection: 'row', gap: 8 },
  optionRowWrap: { flexWrap: 'wrap' },
  optionButton: {
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: 8,
  },
  optionButtonWrap: { flexBasis: '30%', flexGrow: 1 },
  optionText: { fontSize: 13, fontWeight: '700', textAlign: 'center' },
  optionTextSelected: { color: '#FFFFFF' },
  descriptionInput: {
    borderRadius: 8,
    borderWidth: 1,
    fontSize: 14,
    minHeight: 92,
    padding: 12,
    textAlignVertical: 'top',
  },
  characterCount: { alignSelf: 'flex-end', fontSize: 11 },
  consentRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    minHeight: 36,
  },
  checkbox: {
    alignItems: 'center',
    borderRadius: 4,
    borderWidth: 1.5,
    height: 22,
    justifyContent: 'center',
    width: 22,
  },
  consentText: { flex: 1, fontSize: 13, lineHeight: 19 },
  costSummary: {
    alignItems: 'center',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 12,
    padding: 12,
  },
  costSummaryCopy: { flex: 1, gap: 3 },
  costSummaryTitle: { fontSize: 13, fontWeight: '700', lineHeight: 19 },
  costSummaryHint: { fontSize: 11, lineHeight: 17 },
  costSummaryValue: { fontSize: 14, fontWeight: '700' },
  footer: { borderTopWidth: 2, paddingHorizontal: 18, paddingVertical: 12 },
  primaryButton: {
    alignItems: 'center',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 16,
  },
  primaryButtonText: { color: '#FFFFFF', fontSize: 15, fontWeight: '700' },
  buttonDisabled: { opacity: 0.42 },
  buttonPressed: { opacity: 0.82 },
  errorNotice: {
    alignItems: 'flex-start',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    margin: 16,
    padding: 12,
  },
  errorText: { flex: 1, fontSize: 12, lineHeight: 18 },
  jobContent: { paddingBottom: 24 },
  progressSection: {
    alignItems: 'center',
    borderBottomWidth: 2,
    paddingHorizontal: 24,
    paddingVertical: 34,
  },
  jobIcon: {
    alignItems: 'center',
    borderRadius: 8,
    height: 60,
    justifyContent: 'center',
    marginBottom: 18,
    width: 60,
  },
  jobTitle: { fontSize: 21, fontWeight: '700', textAlign: 'center' },
  jobBody: { fontSize: 13, lineHeight: 20, marginTop: 8, textAlign: 'center' },
  progressTrack: {
    borderRadius: 4,
    height: 8,
    marginTop: 24,
    overflow: 'hidden',
    width: '100%',
  },
  progressFill: { borderRadius: 4, height: '100%' },
  progressValue: { fontSize: 12, marginTop: 8 },
  referenceSection: { borderBottomWidth: 2, padding: 18 },
  referenceTitle: { fontSize: 17, fontWeight: '700' },
  referenceHint: { fontSize: 12, lineHeight: 18, marginTop: 6 },
  referenceGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 16,
  },
  referenceItem: {
    aspectRatio: 0.82,
    borderRadius: 8,
    flexBasis: '48%',
    flexGrow: 1,
    overflow: 'hidden',
  },
  referenceImage: { height: '100%', width: '100%' },
  referenceLabel: {
    backgroundColor: 'rgba(0,0,0,0.66)',
    bottom: 0,
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
    left: 0,
    paddingHorizontal: 8,
    paddingVertical: 5,
    position: 'absolute',
    right: 0,
  },
  referenceLoading: {
    alignItems: 'center',
    height: 220,
    justifyContent: 'center',
  },
  referenceQuality: {
    borderTopWidth: 2,
    gap: 10,
    marginTop: 18,
    paddingTop: 18,
  },
  referenceQualityTitle: { fontSize: 16, fontWeight: '700' },
  referenceQualityHint: { fontSize: 12, lineHeight: 18, minHeight: 18 },
  qualitySegment: { flexDirection: 'row', gap: 8 },
  qualitySegmentButton: {
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: 10,
  },
  qualitySegmentLabel: { fontSize: 13, fontWeight: '700' },
  referenceActions: { flexDirection: 'row', gap: 10 },
  secondaryButton: {
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 18,
  },
  secondaryButtonText: { fontSize: 14, fontWeight: '700' },
  referencePrimaryButton: { flex: 1 },
  cancelCommand: {
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: 16,
    padding: 12,
  },
  cancelCommandText: { fontSize: 13, fontWeight: '700' },
  managerContent: { paddingBottom: 20 },
  managerSummary: {
    alignItems: 'center',
    borderBottomWidth: 2,
    flexDirection: 'row',
    gap: 12,
    padding: 18,
  },
  managerIcon: {
    alignItems: 'center',
    borderRadius: 8,
    height: 58,
    justifyContent: 'center',
    width: 58,
  },
  managerSummaryCopy: { flex: 1, gap: 4 },
  managerTitle: { fontSize: 18, fontWeight: '700' },
  managerSubtitle: { fontSize: 12 },
  newModelButton: {
    alignItems: 'center',
    borderRadius: 8,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  modelList: { marginTop: 10 },
  modelRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    marginHorizontal: 18,
    minHeight: 86,
    paddingVertical: 12,
  },
  modelRowDivider: { borderBottomWidth: 2 },
  modelThumbnail: {
    alignItems: 'center',
    borderRadius: 8,
    height: 62,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 62,
  },
  modelThumbnailImage: { height: '100%', width: '100%' },
  modelCopy: { flex: 1, gap: 5 },
  modelTitle: { fontSize: 15, fontWeight: '700' },
  modelMeta: { fontSize: 12 },
  deleteButton: {
    alignItems: 'center',
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  managerEmpty: {
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 30,
    paddingTop: 100,
  },
  managerEmptyTitle: { fontSize: 17, fontWeight: '700' },
});
