import { spacing } from '../theme';

export const stationAvatarStyles = {
  avatarSpace: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    overflow: 'hidden',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 18,
  },
  avatarFloatingPill: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 9,
    position: 'absolute',
    shadowColor: 'rgba(0,0,0,0.16)',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 14,
    zIndex: 5,
  },
  avatarFloatingPillLeft: { left: 24, top: 72 },
  avatarFloatingPillRight: { right: 24, top: 102 },
  avatarFloatingPillBottom: { left: 32, top: 210 },
  avatarFloatingPillText: { fontSize: 12, fontWeight: '900' },
  characterShadow3d: {
    backgroundColor: 'rgba(0,0,0,0.14)',
    borderRadius: 78,
    bottom: 24,
    height: 26,
    left: '50%',
    marginLeft: -68,
    position: 'absolute',
    transform: [{ scaleX: 1.18 }],
    width: 136,
  },
  characterRig: {
    height: 268,
    left: '50%',
    marginLeft: -72,
    position: 'absolute',
    top: 25,
    width: 144,
  },
  characterBackHair: {
    borderRadius: 30,
    height: 78,
    left: '50%',
    marginLeft: -42,
    position: 'absolute',
    top: 42,
    width: 84,
  },
  characterHead: {
    backgroundColor: '#fccca0',
    borderRadius: 37,
    height: 74,
    left: '50%',
    marginLeft: -37,
    position: 'absolute',
    top: 34,
    width: 74,
    zIndex: 5,
  },
  characterHeadSide: {
    borderBottomRightRadius: 38,
    borderTopRightRadius: 38,
    bottom: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    width: 22,
  },
  characterHead3d: {
    borderColor: 'rgba(255,255,255,0.45)',
    borderLeftWidth: 2,
    shadowColor: '#000000',
    shadowOffset: { height: 9, width: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    transform: [{ rotateX: '8deg' }],
  },
  characterHair: {
    borderRadius: 13,
    height: 32,
    left: -10,
    position: 'absolute',
    top: -18,
    width: 94,
  },
  characterHair_short: { height: 30, left: -6, top: -14, width: 86 },
  characterHair_bob: {
    borderRadius: 24,
    height: 54,
    left: -8,
    top: -14,
    width: 90,
  },
  characterHair_wave: {
    borderRadius: 28,
    height: 44,
    left: -12,
    top: -18,
    transform: [{ rotate: '-5deg' }],
    width: 98,
  },
  characterHair_curly: {
    borderRadius: 999,
    height: 42,
    left: -8,
    top: -20,
    width: 90,
  },
  characterHair_undercut: {
    borderRadius: 12,
    height: 24,
    left: 8,
    top: -12,
    transform: [{ skewX: '-12deg' }],
    width: 70,
  },
  characterHairCurls: {
    borderRadius: 999,
    height: 18,
    left: 6,
    position: 'absolute',
    top: -12,
    width: 62,
  },
  characterCapBrim: {
    borderRadius: 999,
    height: 16,
    left: -4,
    position: 'absolute',
    top: 8,
    transform: [{ rotate: '-4deg' }],
    width: 84,
  },
  characterCapLetter: {
    fontSize: 13,
    fontWeight: '900',
    left: 34,
    position: 'absolute',
    top: -9,
  },
  characterEyeLeft: {
    backgroundColor: '#1a1f1c',
    borderRadius: 5,
    height: 9,
    left: 22,
    position: 'absolute',
    top: 31,
    width: 9,
  },
  characterEyeRight: {
    backgroundColor: '#1a1f1c',
    borderRadius: 5,
    height: 9,
    position: 'absolute',
    right: 22,
    top: 31,
    width: 9,
  },
  characterMouth: {
    borderColor: '#1a1f1c',
    left: 25,
    position: 'absolute',
    top: 52,
  },
  characterMouthSmile: {
    borderBottomWidth: 2,
    borderRadius: 6,
    height: 10,
    width: 24,
  },
  characterMouthCalm: { borderTopWidth: 2, height: 1, top: 56, width: 24 },
  characterMouthFocus: {
    borderTopWidth: 2,
    height: 1,
    left: 29,
    top: 56,
    width: 16,
  },
  characterAccessorySpark: {
    fontSize: 20,
    fontWeight: '900',
    position: 'absolute',
    right: -10,
    top: -12,
  },
  characterAccessoryCap: {
    borderRadius: 999,
    height: 12,
    left: 17,
    position: 'absolute',
    top: -10,
    width: 40,
  },
  characterGlasses: {
    borderColor: '#1a1f1c',
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderTopWidth: 2,
    height: 15,
    left: 18,
    position: 'absolute',
    top: 29,
    width: 38,
  },
  characterHeadphones: {
    borderRadius: 24,
    borderTopWidth: 4,
    height: 36,
    left: 10,
    position: 'absolute',
    top: 4,
    width: 54,
  },
  characterBody: {
    borderRadius: 22,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    height: 104,
    left: '50%',
    marginLeft: -45,
    position: 'absolute',
    top: 110,
    width: 90,
    zIndex: 3,
  },
  characterBodySide: {
    borderBottomRightRadius: 24,
    borderTopRightRadius: 24,
    bottom: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    width: 22,
  },
  characterArmLeft: {
    backgroundColor: '#1a1f1c',
    borderRadius: 13,
    height: 83,
    left: 23,
    position: 'absolute',
    top: 119,
    transform: [{ rotate: '-13deg' }],
    width: 22,
    zIndex: 2,
  },
  characterArmRight: {
    backgroundColor: '#1a1f1c',
    borderRadius: 13,
    height: 83,
    position: 'absolute',
    right: 23,
    top: 119,
    transform: [{ rotate: '16deg' }],
    width: 22,
    zIndex: 2,
  },
  characterHand: {
    borderRadius: 999,
    bottom: -8,
    height: 24,
    left: -1,
    position: 'absolute',
    width: 24,
  },
  characterBodyHighlight: {
    borderRadius: 18,
    height: 56,
    left: 13,
    opacity: 0.24,
    position: 'absolute',
    top: 22,
    width: 20,
  },
  characterNeck: {
    backgroundColor: '#e7ad82',
    borderRadius: 10,
    height: 22,
    left: '50%',
    marginLeft: -12,
    position: 'absolute',
    top: 96,
    width: 24,
    zIndex: 4,
  },
  characterCollar: {
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
    height: 18,
    left: '50%',
    marginLeft: -18,
    position: 'absolute',
    top: -1,
    width: 36,
  },
  characterPanel: {
    backgroundColor: '#1a1f1c',
    borderRadius: 12,
    height: 52,
    left: 31,
    position: 'absolute',
    top: 30,
    width: 28,
  },
  characterLegs: {
    flexDirection: 'row',
    gap: 15,
    left: '50%',
    marginLeft: -33,
    position: 'absolute',
    top: 201,
    zIndex: 1,
  },
  characterLegColumn: { alignItems: 'center', gap: 0 },
  characterLeg: {
    backgroundColor: '#1a1f1c',
    borderRadius: 10,
    height: 48,
    width: 25,
  },
  characterShoe: { borderRadius: 999, height: 12, marginTop: -1, width: 34 },
  avatarSpaceCopy: { gap: 6, padding: 14 },
  avatarSpaceTitleRow: { alignItems: 'center', flexDirection: 'row', gap: 10 },
  avatarSpaceTitleCopy: { flex: 1, gap: 4 },
  avatarSpaceEyebrow: { fontSize: 12, fontWeight: '900' },
  avatarSpaceTitle: { fontSize: 20, fontWeight: '900' },
  avatarSpaceBody: { fontSize: 12, lineHeight: 18 },
  avatarFloatingTags: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 8,
  },
  avatarFloatingTag: {
    alignItems: 'center',
    borderRadius: 999,
    justifyContent: 'center',
    minHeight: 28,
    paddingHorizontal: 10,
    position: 'absolute',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 16,
  },
  avatarFloatingTag_0: { left: 20, top: 52 },
  avatarFloatingTag_1: { right: 18, top: 74 },
  avatarFloatingTag_2: { left: 24, top: 174 },
  avatarFloatingTag_3: { right: 28, top: 190 },
  avatarFloatingTagCallable: { minHeight: 32, paddingHorizontal: 12 },
  avatarFloatingTagText: { fontSize: 12, fontWeight: '900' },
  avatarOotdButton: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    marginTop: 6,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  avatarOotdButtonText: { fontSize: 12, fontWeight: '900' },
  avatarRotateControls: {
    bottom: 16,
    flexDirection: 'row',
    gap: 10,
    position: 'absolute',
    right: 16,
    zIndex: 10,
  },
  avatarRotateButton: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    shadowOffset: { height: 5, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    width: 38,
  },
} as const;
