import { spacing } from '../theme';

export const stationLayoutStyles = {
  stationPanelScroll: { flex: 1 },
  stationScrollContent: { paddingBottom: 118 },
  stationTopContent: {
    paddingBottom: 8,
    paddingHorizontal: 14,
    paddingTop: 10,
  },
  stationPanelWrap: { paddingHorizontal: 14, paddingTop: 8 },
  stationTabHeader: {
    borderBottomWidth: 0,
    paddingHorizontal: 8,
    zIndex: 20,
  },
  stationPanelStack: { gap: 12 },
  stationPageHeading: {
    minHeight: 76,
    overflow: 'hidden',
    paddingHorizontal: 2,
    paddingTop: 14,
    position: 'relative',
  },
  stationPageTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingTop: 13,
  },
  stationPageTitle: { fontSize: 23, fontWeight: '800' },
  stationPageDetail: {
    borderRadius: 3,
    fontSize: 9,
    fontWeight: '800',
    overflow: 'hidden',
    paddingHorizontal: 6,
    paddingVertical: 3,
  },
  stationPageWatermark: {
    fontSize: 32,
    fontWeight: '900',
    left: 0,
    opacity: 0.62,
    position: 'absolute',
    top: 27,
  },
  stationOutcomeEmpty: { borderRadius: 8, gap: 6, padding: 18 },
  stationOutcomeEmptyTitle: { fontSize: 15, fontWeight: '900' },
  stationOutcomeEmptyBody: { fontSize: 12, lineHeight: 18 },
  stationOutcomeHero: {
    backgroundColor: '#E6EBFF',
    borderRadius: 4,
    flexDirection: 'row',
    minHeight: 174,
    overflow: 'hidden',
    padding: 18,
  },
  stationOutcomeHeroCopy: { flex: 1, gap: 7, justifyContent: 'center' },
  stationOutcomeHeroLabel: {
    color: '#000000',
    fontSize: 14,
    fontWeight: '700',
  },
  stationOutcomeHeroValue: {
    color: '#2012D9',
    fontSize: 46,
    fontWeight: '700',
  },
  stationOutcomeHeroTrend: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 5,
  },
  stationOutcomeHeroTrendText: { color: 'rgba(0,0,0,0.60)', fontSize: 11 },
  stationOutcomeHeroMark: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 112,
  },
  stationOutcomeAwardOuter: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.55)',
    borderRadius: 20,
    height: 92,
    justifyContent: 'center',
    transform: [{ rotate: '-10deg' }],
    width: 92,
  },
  stationOutcomeAwardInner: {
    alignItems: 'center',
    backgroundColor: '#6797F3',
    borderRadius: 15,
    height: 62,
    justifyContent: 'center',
    width: 62,
  },
  stationOutcomeMetrics: {
    borderBottomLeftRadius: 4,
    borderBottomRightRadius: 4,
    flexDirection: 'row',
    marginTop: -12,
    padding: 12,
  },
  stationOutcomeSectionHead: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  stationOutcomeFilters: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  stationOutcomeFilter: {
    backgroundColor: '#FFFFFF',
    borderRadius: 999,
    minHeight: 27,
    paddingHorizontal: 12,
    justifyContent: 'center',
  },
  stationOutcomeFilterActive: { backgroundColor: '#2012D9' },
  stationOutcomeFilterText: { color: 'rgba(0,0,0,0.58)', fontSize: 11 },
  stationOutcomeFilterTextActive: { color: '#FFFFFF', fontWeight: '700' },
  stationOutcomeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  stationOutcomeCard: {
    borderRadius: 4,
    gap: 5,
    overflow: 'hidden',
    paddingBottom: 12,
    width: '48.8%',
  },
  stationOutcomeCardFeatured: { width: '100%' },
  stationOutcomeVisual: {
    alignItems: 'center',
    height: 112,
    justifyContent: 'center',
    marginBottom: 3,
  },
  stationOutcomeVisualBlue: { backgroundColor: '#E5EDFF' },
  stationOutcomeVisualRose: { backgroundColor: '#F7EAF1' },
  stationOutcomeKind: { fontSize: 10, paddingHorizontal: 10 },
  stationOutcomeTitle: {
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 19,
    paddingHorizontal: 10,
  },
  stationOutcomeSummary: {
    fontSize: 11,
    lineHeight: 16,
    paddingHorizontal: 10,
  },
  stationModuleCard: {
    borderRadius: 4,
    gap: 12,
    padding: 14,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
  },
  stationModuleTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  stationModuleTitle: { flex: 1, fontSize: 16, fontWeight: '900' },
  stationModuleActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  stationModuleAgentButton: {
    alignItems: 'center',
    borderRadius: 999,
    flexDirection: 'row',
    gap: 5,
    height: 28,
    maxWidth: 126,
    paddingHorizontal: 9,
  },
  stationModuleAgentButtonPending: { opacity: 0.56 },
  stationModuleAgentText: { flexShrink: 1, fontSize: 11, fontWeight: '800' },
  stationModuleAddButton: {
    alignItems: 'center',
    borderRadius: 999,
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  stationModuleAddText: { fontSize: 12, fontWeight: '900' },
  stationModuleTextButton: { paddingHorizontal: 10, width: 'auto' },
  stationModuleMoreButton: {
    alignItems: 'center',
    borderRadius: 999,
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  stationModuleStack: { gap: 12 },
  stationMiniPanel: {
    borderRadius: 3,
    flexBasis: '48%',
    flexGrow: 1,
    overflow: 'hidden',
    position: 'relative',
  },
  stationMiniPanelMorning: { backgroundColor: '#f7f7f7' },
  stationMiniPanelNoon: { backgroundColor: '#e9e9e9' },
  stationMiniPanelEvening: { backgroundColor: '#dcdcdc' },
  stationMiniPanelNight: { backgroundColor: '#252525' },
  stationAlbumGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  stationAlbumTile: { gap: 5, minWidth: 96, width: '31%' },
  stationAlbumCover: {
    alignItems: 'center',
    aspectRatio: 1,
    borderRadius: spacing.cardRadius,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  stationAlbumCoverImage: {
    height: '100%',
    width: '100%',
  },
  stationAlbumCoverText: { fontSize: 11, fontWeight: '900' },
  stationAlbumTitle: { fontSize: 13, fontWeight: '900' },
  stationAlbumCount: { fontSize: 11, fontWeight: '700' },
  stationManageTextArea: {
    minHeight: 132,
    textAlignVertical: 'top',
  },
  stationManagePhotoHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  stationManageSmallButton: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    minHeight: 32,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  stationManageSmallButtonText: { fontSize: 12, fontWeight: '900' },
  stationManageMediaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  stationManageMediaItem: {
    alignItems: 'center',
    aspectRatio: 1,
    borderRadius: spacing.cardRadius,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: '31.6%',
  },
  stationManageMediaImage: { height: '100%', width: '100%' },
  stationManageMediaDelete: {
    alignItems: 'center',
    borderRadius: 999,
    bottom: 6,
    minHeight: 26,
    justifyContent: 'center',
    paddingHorizontal: 9,
    position: 'absolute',
    right: 6,
  },
  stationManageMediaDeleteText: { fontSize: 11, fontWeight: '900' },
  stationContentListScreen: { flex: 1 },
  stationEditorScreen: { flex: 1 },
  stationEditorKeyboard: { flex: 1 },
  stationEditorHeader: {
    alignItems: 'center',
    borderBottomWidth: 1,
    flexDirection: 'row',
    height: 58,
  },
  stationEditorHeaderSide: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 72,
  },
  stationEditorBackIcon: { height: 22, width: 22 },
  stationEditorHeaderTitle: {
    flex: 1,
    fontSize: 17,
    fontWeight: '800',
    textAlign: 'center',
  },
  stationEditorSaveButton: {
    alignItems: 'center',
    borderRadius: 6,
    justifyContent: 'center',
    minHeight: 32,
    minWidth: 54,
    paddingHorizontal: 10,
  },
  stationEditorPrimaryBackground: { backgroundColor: '#2012D9' },
  stationEditorSaveText: { color: '#FFFFFF', fontSize: 13, fontWeight: '800' },
  stationEditorBody: { paddingBottom: 40 },
  stationCreateComposer: {
    minHeight: 280,
    paddingBottom: 18,
    paddingHorizontal: 18,
    paddingTop: 16,
  },
  stationCreateDiaryInput: {
    fontSize: 16,
    lineHeight: 25,
    minHeight: 250,
    padding: 0,
  },
  stationCreateAlbumTitleInput: {
    fontSize: 20,
    fontWeight: '700',
    minHeight: 48,
    padding: 0,
  },
  stationCreateAlbumDescriptionInput: {
    fontSize: 14,
    lineHeight: 21,
    minHeight: 96,
    padding: 0,
    textAlignVertical: 'top',
  },
  stationCreateMediaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 14,
  },
  stationCreateMediaItem: {
    borderRadius: 4,
    height: 96,
    overflow: 'hidden',
    position: 'relative',
    width: 96,
  },
  stationCreateMediaImage: { height: '100%', width: '100%' },
  stationCreateMediaRemove: {
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.62)',
    borderRadius: 999,
    height: 22,
    justifyContent: 'center',
    position: 'absolute',
    right: 4,
    top: 4,
    width: 22,
  },
  stationCreateMediaAdd: {
    alignItems: 'center',
    borderRadius: 4,
    borderStyle: 'dashed',
    borderWidth: 1,
    gap: 3,
    height: 96,
    justifyContent: 'center',
    width: 96,
  },
  stationCreateMediaAddText: { fontSize: 11, fontWeight: '600' },
  stationCreateVisibilityRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    minHeight: 54,
    marginTop: 8,
    paddingHorizontal: 18,
  },
  stationCreateVisibilityTitle: { flex: 1, fontSize: 14, fontWeight: '600' },
  stationCreateVisibilityValue: { fontSize: 12 },
  stationEditorSection: {
    borderBottomWidth: 2,
    gap: 16,
    paddingHorizontal: 18,
    paddingVertical: 18,
  },
  stationEditorSectionTitle: { fontSize: 17, fontWeight: '900' },
  stationEditorField: { gap: 8 },
  stationEditorFieldLabel: { fontSize: 13, fontWeight: '700' },
  stationEditorInput: {
    borderRadius: 6,
    borderWidth: 1,
    fontSize: 15,
    minHeight: 46,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  stationEditorTextArea: { minHeight: 150, textAlignVertical: 'top' },
  stationEditorDeleteButton: {
    alignItems: 'center',
    borderRadius: 6,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 44,
  },
  stationEditorDeleteText: { fontSize: 14, fontWeight: '800' },
  stationEditorVisibilityRow: {
    alignItems: 'center',
    borderRadius: 4,
    flexDirection: 'row',
    gap: 10,
    minHeight: 48,
    paddingHorizontal: 12,
  },
  stationContentListHeader: {
    alignItems: 'center',
    borderBottomWidth: 1,
    flexDirection: 'row',
    height: 58,
  },
  stationContentListAdd: {
    alignItems: 'center',
    borderRadius: 999,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  stationContentListBody: { gap: 10, padding: 16, paddingBottom: 40 },
  stationContentFilters: {
    flexDirection: 'row',
    gap: 6,
    padding: 10,
  },
  stationContentFilter: {
    alignItems: 'center',
    borderRadius: 4,
    flex: 1,
    justifyContent: 'center',
    minHeight: 34,
  },
  stationContentFilterSelected: { backgroundColor: '#F4F6FF' },
  stationContentFilterText: { fontSize: 12, fontWeight: '700' },
  stationContentFilterTextSelected: { color: '#2012D9' },
  stationContentMonthGroup: { gap: 8 },
  stationContentMonthTitle: { fontSize: 12, fontWeight: '700', paddingLeft: 2 },
  stationContentMonthItems: { gap: 8 },
  stationContentListEmpty: {
    borderRadius: spacing.cardRadius,
    gap: 6,
    padding: 16,
  },
  stationContentListEmptyTitle: { fontSize: 16, fontWeight: '900' },
  stationContentListEmptyBody: { fontSize: 13, lineHeight: 19 },
  stationContentSwipeTrack: {
    borderRadius: spacing.cardRadius,
    overflow: 'hidden',
    position: 'relative',
  },
  stationContentSwipeAction: {
    alignItems: 'center',
    bottom: 0,
    gap: 4,
    justifyContent: 'center',
    position: 'absolute',
    right: 0,
    top: 0,
    width: 72,
  },
  stationContentSwipeActionText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '900',
  },
  stationContentListRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    minHeight: 104,
    padding: 12,
  },
  stationContentListCover: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    height: 80,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 80,
  },
  stationContentListCoverImage: { height: '100%', width: '100%' },
  stationContentListCoverText: { fontSize: 22, fontWeight: '900' },
  stationContentListCopy: { flex: 1, gap: 5, minWidth: 0 },
  stationContentListTitle: { fontSize: 16, fontWeight: '900' },
  stationContentListSummary: { fontSize: 12, lineHeight: 18 },
  stationContentListMeta: { fontSize: 11, fontWeight: '700' },
  stationContentDetailHero: {
    borderBottomWidth: 2,
    gap: 10,
    paddingHorizontal: 20,
    paddingVertical: 22,
  },
  stationContentDetailTitle: {
    fontSize: 24,
    fontWeight: '800',
    lineHeight: 32,
  },
  stationContentDetailMeta: { fontSize: 12, lineHeight: 18 },
  stationContentDetailBody: { fontSize: 16, lineHeight: 27, paddingTop: 8 },
  stationAIPartnerGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  stationAIPartnerTile: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    flexBasis: '47%',
    flexDirection: 'column',
    flexGrow: 0,
    gap: 8,
    justifyContent: 'center',
    minHeight: 116,
    padding: 12,
  },
  stationAIPartnerCopy: {
    alignItems: 'center',
    gap: 3,
    minWidth: 0,
    width: '100%',
  },
  stationAIPartnerName: {
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
  },
  stationAIPartnerDesc: {
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 15,
    textAlign: 'center',
  },
  stationModuleEmpty: {
    borderRadius: spacing.cardRadius,
    gap: 5,
    minHeight: 88,
    padding: 12,
  },
  stationModuleEmptyMeta: { fontSize: 11, fontWeight: '900' },
  stationModuleEmptyTitle: { fontSize: 13, fontWeight: '900' },
  stationModuleEmptyBody: { fontSize: 12, fontWeight: '700', lineHeight: 18 },
  stationEcosystemHero: {
    backgroundColor: '#E6EBFF',
    borderRadius: 4,
    gap: 14,
    minHeight: 250,
    padding: 18,
  },
  stationEcosystemScoreBlock: { gap: 5 },
  stationEcosystemEyebrow: { color: 'rgba(0,0,0,0.56)', fontSize: 12 },
  stationEcosystemScore: { color: '#000000', fontSize: 46, fontWeight: '500' },
  stationEcosystemScoreLabel: {
    color: '#2012D9',
    fontSize: 12,
    fontWeight: '700',
  },
  stationEcosystemProgressBlock: { gap: 8 },
  stationEcosystemProgressTitle: {
    color: '#000000',
    fontSize: 14,
    fontWeight: '700',
  },
  stationEcosystemProgressTrack: {
    backgroundColor: 'rgba(255,255,255,0.74)',
    borderRadius: 999,
    height: 10,
    overflow: 'hidden',
  },
  stationEcosystemProgressFill: {
    backgroundColor: '#6797F3',
    borderRadius: 999,
    height: '100%',
  },
  stationEcosystemProgressMeta: { color: 'rgba(0,0,0,0.55)', fontSize: 11 },
  stationPartnerMetrics: { flexDirection: 'row', gap: 8 },
  stationMetricBox: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    flex: 1,
    gap: 2,
    minHeight: 58,
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  stationMetricValue: { fontSize: 18, fontWeight: '900' },
  stationMetricLabel: { fontSize: 11, fontWeight: '800' },
  stationSectionTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  stationSectionTitle: { flex: 1, fontSize: 16, fontWeight: '900' },
  stationSectionDetail: { fontSize: 12, fontWeight: '700' },
  stationSectionPill: {
    borderRadius: 999,
    fontSize: 12,
    fontWeight: '800',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  stationRecommendAgents: { gap: 10, marginTop: 4 },
  stationRadarCard: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  stationRadarMetrics: { flexDirection: 'row', gap: 8 },
  stationCard: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 12,
    padding: 14,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 16,
  },
  stationCardHeader: { alignItems: 'center', flexDirection: 'row', gap: 12 },
  stationCardTitle: { flex: 1, fontSize: 15, fontWeight: '900' },
  stationCardDetail: { fontSize: 12, fontWeight: '700' },
  stationPlaceholder: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    gap: 10,
    justifyContent: 'center',
    minHeight: 150,
    padding: 14,
  },
  miaoShowAvatarWrap: { alignItems: 'center', justifyContent: 'center' },
} as const;
