import { spacing } from '../theme';

export const stationProfileStyles = {
  stationIdentityCard: {
    borderRadius: 4,
    gap: 12,
    padding: 12,
  },
  stationIdentityTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  stationIdentityAvatar: {
    borderRadius: 4,
    height: 60,
    overflow: 'hidden',
    width: 60,
  },
  stationIdentityCopy: { flex: 1, gap: 3, minWidth: 0 },
  stationIdentityEditButton: {
    alignItems: 'center',
    borderRadius: 999,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  stationIdentityName: { fontSize: 16, fontWeight: '600', lineHeight: 22 },
  stationIdentityIdRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 5,
    minWidth: 0,
  },
  stationIdentityId: { fontSize: 11, lineHeight: 15 },
  stationIdentityQr: {
    alignItems: 'center',
    height: 18,
    justifyContent: 'center',
    width: 18,
  },
  stationIdentityPresenceRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
  },
  stationIdentityPresenceDot: { borderRadius: 999, height: 6, width: 6 },
  stationIdentityPresenceDotOnline: { backgroundColor: '#20B26B' },
  stationIdentityPresenceDotOffline: { backgroundColor: '#E24B4B' },
  stationIdentityPresenceText: { fontSize: 10, fontWeight: '600' },
  stationIdentityPresenceTextOnline: { color: '#2012D9' },
  stationIdentityStats: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  stationIdentityStat: {
    alignItems: 'baseline',
    flexDirection: 'row',
    flexWrap: 'wrap',
    flex: 1,
    gap: 6,
    minWidth: 0,
  },
  stationIdentityStatValue: { fontSize: 18, fontWeight: '600' },
  stationIdentityStatLabel: { fontSize: 10, lineHeight: 14 },
  stationIdentityHeadline: { fontSize: 12, fontWeight: '500', lineHeight: 17 },
  stationIdentityBio: { fontSize: 12, lineHeight: 18 },
  stationIdentityTags: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  stationIdentityTag: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 4,
    minHeight: 26,
    maxWidth: '100%',
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  stationIdentityTagText: {
    fontSize: 11,
    fontWeight: '400',
    flexShrink: 1,
    lineHeight: 16,
  },
  stationNavRow: { alignItems: 'stretch', flexDirection: 'row' },
  stationTabsViewport: { flex: 1, minWidth: 0 },
  stationTabs: {
    alignItems: 'stretch',
    flexDirection: 'row',
    gap: 2,
    paddingHorizontal: 4,
  },
  stationTabButton: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 46,
    minWidth: 64,
    paddingHorizontal: 10,
    position: 'relative',
  },
  stationTabLabelRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 3,
    justifyContent: 'center',
  },
  stationTabText: { textAlign: 'center' },
  stationTabTextActive: { fontSize: 12, fontWeight: '700' },
  stationTabTextInactive: { fontSize: 11, fontWeight: '400' },
  stationTabIndicator: {
    backgroundColor: '#2012D9',
    borderRadius: 2,
    bottom: 3,
    height: 3,
    position: 'absolute',
    width: 22,
  },
  stationNavSettings: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 38,
  },
  stationNavSettingsIcon: { height: 7, width: 27 },
  profileDataRow: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  profileDataTitle: { fontSize: 12, fontWeight: '700' },
  profileDataValue: {
    flex: 1,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'right',
  },
  locationHero: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 10,
    marginHorizontal: 14,
    padding: 14,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 16,
  },
  locationHeroTitle: { fontSize: 24, fontWeight: '900' },
  locationHeroDetail: { fontSize: 14, fontWeight: '800' },
  locationStatusText: { fontSize: 12, fontWeight: '700', lineHeight: 18 },
  locationSection: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 9,
    marginHorizontal: 14,
    padding: 12,
  },
  locationSectionTitle: { fontSize: 12, fontWeight: '900' },
  locationCandidate: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 50,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  locationCandidateCopy: { flex: 1, gap: 3 },
  locationCandidateName: { fontSize: 14, fontWeight: '900' },
  locationCandidateDetail: { fontSize: 11, fontWeight: '700' },
  locationSelectedDot: { borderRadius: 999, height: 10, width: 10 },
  locationEmptyText: { fontSize: 12, fontWeight: '700', lineHeight: 18 },
} as const;
