export const stationPostStyles = {
  postComposerScreen: { flex: 1 },
  postComposerKeyboard: { flex: 1 },
  postComposerHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    height: 58,
  },
  postComposerBack: {
    alignItems: 'center',
    height: 58,
    justifyContent: 'center',
    width: 68,
  },
  postComposerBackIcon: { height: 22, width: 22 },
  postComposerTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  postComposerPublishSlot: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 68,
  },
  postComposerPublish: {
    alignItems: 'center',
    borderRadius: 16,
    justifyContent: 'center',
    minHeight: 32,
    minWidth: 56,
    paddingHorizontal: 10,
  },
  postComposerPublishText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '600',
  },
  postComposerPublishProgress: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 3,
  },
  postComposerPublishProgressText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '600',
  },
  postComposerScrollContent: {
    gap: 8,
    paddingBottom: 24,
    paddingHorizontal: 12,
    paddingTop: 8,
  },
  postComposerEditorCard: {
    borderRadius: 4,
    overflow: 'hidden',
  },
  postComposerInput: {
    fontSize: 13,
    lineHeight: 20,
    padding: 0,
    paddingBottom: 12,
    paddingHorizontal: 16,
    paddingTop: 15,
  },
  postComposerInputText: { minHeight: 182 },
  postComposerInputImage: { minHeight: 216 },
  postComposerInputVideo: { minHeight: 147 },
  postComposerMediaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingBottom: 20,
    paddingHorizontal: 16,
  },
  postComposerMediaItem: {
    borderRadius: 3,
    height: 94,
    overflow: 'hidden',
    position: 'relative',
    width: 94,
  },
  postComposerMediaImage: { height: '100%', width: '100%' },
  postComposerMediaAdd: {
    alignItems: 'center',
    borderRadius: 3,
    borderStyle: 'dashed',
    borderWidth: 1,
    height: 94,
    justifyContent: 'center',
    width: 94,
  },
  postComposerMediaRemove: {
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.62)',
    borderRadius: 999,
    height: 22,
    justifyContent: 'center',
    position: 'absolute',
    right: 4,
    top: 4,
    width: 22,
  },
  postComposerVideoMedia: {
    alignItems: 'center',
    borderRadius: 3,
    gap: 8,
    height: 163,
    justifyContent: 'center',
    marginBottom: 20,
    marginHorizontal: 25,
    overflow: 'hidden',
    padding: 20,
    position: 'relative',
  },
  postComposerVideoEntryIcon: { height: 58, width: 58 },
  postComposerVideoName: {
    fontSize: 12,
    lineHeight: 17,
    maxWidth: '90%',
    textAlign: 'center',
  },
  postComposerMediaToolbar: {
    alignItems: 'center',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 27,
    height: 42,
    paddingHorizontal: 16,
  },
  postComposerMediaAction: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 5,
    height: 42,
    justifyContent: 'center',
  },
  postComposerMediaActionIcon: { height: 16, width: 16 },
  postComposerMediaActionText: { fontSize: 12, fontWeight: '500' },
  postComposerSectionCard: {
    borderRadius: 4,
    padding: 16,
  },
  postComposerSectionTitle: {
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 21,
  },
  postComposerSectionDescription: {
    fontSize: 11,
    lineHeight: 16,
    marginTop: 2,
  },
  postComposerAttachmentRow: {
    alignItems: 'center',
    borderRadius: 4,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 11,
    marginTop: 10,
    minHeight: 72,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  postComposerAttachmentIcon: { height: 46, width: 46 },
  postComposerAttachmentCopy: { flex: 1, gap: 3, minWidth: 0 },
  postComposerAttachmentTitle: { fontSize: 14, fontWeight: '600' },
  postComposerAttachmentDescription: { fontSize: 11, lineHeight: 16 },
  postComposerAgentHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
  },
  postComposerAgentHint: {
    flexShrink: 1,
    fontSize: 11,
    lineHeight: 16,
    textAlign: 'right',
  },
  postComposerAgentChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
    marginTop: 11,
  },
  postComposerAgentChip: {
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    maxWidth: '100%',
    minHeight: 31,
    paddingHorizontal: 13,
  },
  postComposerAgentChipText: {
    flexShrink: 1,
    fontSize: 12,
    fontWeight: '500',
  },
  postComposerAgentChipTextSelected: { color: '#FFFFFF' },
  postComposerAgentEmpty: {
    fontSize: 12,
    lineHeight: 18,
    marginTop: 10,
  },
  postComposerSettingsCard: {
    borderRadius: 4,
    overflow: 'hidden',
  },
  postComposerSettingRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    minHeight: 52,
    paddingHorizontal: 16,
  },
  postComposerSettingTitle: {
    flex: 1,
    flexShrink: 1,
    fontSize: 13,
    fontWeight: '500',
  },
  postComposerSettingValue: { fontSize: 12, fontWeight: '400' },
  postComposerSettingDivider: { height: 1, marginLeft: 44 },
  stationFeedStack: { gap: 10 },
  stationFeedEmpty: {
    alignItems: 'center',
    borderRadius: 4,
    justifyContent: 'center',
    minHeight: 170,
    padding: 24,
  },
  stationFeedEmptyTitle: { fontSize: 16, fontWeight: '600' },
  stationFeedCard: {
    borderRadius: 4,
    gap: 12,
    paddingHorizontal: 13,
    paddingTop: 13,
  },
  stationFeedHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  stationFeedAuthor: { flex: 1, gap: 3, minWidth: 0 },
  stationFeedAuthorName: { fontSize: 15, fontWeight: '600' },
  stationFeedTime: { fontSize: 12, lineHeight: 16 },
  stationFeedMore: {
    alignItems: 'center',
    height: 36,
    justifyContent: 'center',
    width: 40,
  },
  stationFeedMoreIcon: { height: 7, width: 27 },
  stationFeedBody: { fontSize: 15, lineHeight: 23 },
  stationFeedLocation: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
  },
  stationFeedLocationText: { flexShrink: 1, fontSize: 11 },
  stationFeedMediaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 5,
  },
  stationFeedMediaItem: {
    aspectRatio: 1,
    borderRadius: 3,
    overflow: 'hidden',
    width: '32.2%',
  },
  stationFeedMediaItemSingle: { aspectRatio: 4 / 3, width: '100%' },
  stationFeedMediaItemDouble: { width: '49.2%' },
  stationFeedMediaImage: { height: '100%', width: '100%' },
  stationFeedVideo: {
    alignItems: 'center',
    flex: 1,
    gap: 8,
    justifyContent: 'center',
  },
  stationFeedVideoPlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(32,18,217,0.88)',
    borderRadius: 999,
    height: 46,
    justifyContent: 'center',
    paddingLeft: 3,
    width: 46,
  },
  stationFeedVideoText: { fontSize: 12 },
  stationFeedAgents: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  stationFeedAgentChip: {
    borderRadius: 4,
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  stationFeedAgentText: { fontSize: 11, fontWeight: '500' },
  stationFeedActions: {
    borderTopWidth: 1,
    flexDirection: 'row',
    minHeight: 44,
  },
  stationFeedAction: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
  },
  stationFeedActionIcon: { height: 18, width: 18 },
  stationFeedActionText: { fontSize: 12 },
} as const;
