import { spacing } from '../theme';

export const stationLayoutStyles = {
  stationScrollContent: { paddingBottom: 154 },
  stationTopContent: {
    paddingBottom: 18,
    paddingHorizontal: 26,
    paddingTop: 18,
  },
  stationPanelWrap: { paddingHorizontal: 14, paddingTop: 16 },
  stationTabHeader: {
    borderBottomWidth: 1,
    paddingHorizontal: 14,
    zIndex: 20,
  },
  stationPanelStack: { gap: 12 },
  stationHomeBio: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 14,
  },
  stationHomeBioCopy: { flex: 1, gap: 6 },
  stationHomeBioTitle: { fontSize: 19, fontWeight: '900' },
  stationHomeBioBody: { fontSize: 13, lineHeight: 19 },
  stationHomeRegionButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderRadius: spacing.cardRadius,
    flexDirection: 'row',
    gap: 4,
    maxWidth: 124,
    minHeight: 34,
    paddingHorizontal: 10,
  },
  stationHomeRegionText: { flexShrink: 1, fontSize: 12, fontWeight: '900' },
  stationShortcutGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  stationShortcutTile: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    flexBasis: '48%',
    flexGrow: 1,
    gap: 8,
    minHeight: 128,
    padding: 12,
  },
  stationShortcutIcon: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  stationShortcutCopy: { gap: 3 },
  stationShortcutTitle: { fontSize: 14, fontWeight: '900' },
  stationShortcutDetail: { fontSize: 12, fontWeight: '800' },
  stationShortcutStatus: {
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 15,
    marginTop: 'auto',
  },
  stationPreviewStack: { gap: 12 },
  stationPreviewSection: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 10,
    padding: 14,
  },
  stationPreviewHeader: { alignItems: 'center', flexDirection: 'row', gap: 10 },
  stationPreviewTitle: { flex: 1, fontSize: 16, fontWeight: '900' },
  stationPreviewAction: {
    alignItems: 'center',
    flexDirection: 'row',
    minHeight: 32,
  },
  stationPreviewActionText: { fontSize: 12, fontWeight: '900' },
  stationModuleCard: {
    borderRadius: spacing.cardRadius,
    gap: 12,
    padding: 14,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 24,
  },
  stationModuleTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  stationModuleTitle: { flex: 1, fontSize: 16, fontWeight: '900' },
  stationModuleAddButton: {
    alignItems: 'center',
    borderRadius: 999,
    height: 28,
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  stationModuleAddText: { fontSize: 12, fontWeight: '900' },
  stationModuleStack: { gap: 12 },
  stationMiniPanel: {
    borderRadius: 3,
    flexBasis: '48%',
    flexGrow: 1,
    overflow: 'hidden',
    position: 'relative',
  },
  stationMiniPanelMorning: { backgroundColor: '#f7f7f7' },
  stationMiniPanelNoon: { backgroundColor: '#e9e9e9' },
  stationMiniPanelEvening: { backgroundColor: '#dcdcdc' },
  stationMiniPanelNight: { backgroundColor: '#252525' },
  stationAlbumGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  stationAlbumTile: { gap: 5, minWidth: 96, width: '31%' },
  stationAlbumCover: {
    alignItems: 'center',
    aspectRatio: 1,
    borderRadius: spacing.cardRadius,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  stationAlbumCoverSelected: { borderWidth: 2 },
  stationAlbumCoverImage: {
    height: '100%',
    width: '100%',
  },
  stationAlbumCoverText: { fontSize: 11, fontWeight: '900' },
  stationAlbumTitle: { fontSize: 13, fontWeight: '900' },
  stationAlbumCount: { fontSize: 11, fontWeight: '700' },
  stationAlbumAddPhoto: {
    alignItems: 'center',
    borderRadius: 999,
    minHeight: 28,
    justifyContent: 'center',
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  stationAlbumAddPhotoText: { fontSize: 11, fontWeight: '900' },
  stationContentDetailPanel: {
    borderRadius: spacing.cardRadius,
    gap: 10,
    padding: 12,
  },
  stationContentDetailHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  stationContentDetailCopy: { flex: 1, gap: 4, minWidth: 0 },
  stationContentDetailTitle: { flex: 1, fontSize: 16, fontWeight: '900' },
  stationContentDetailAction: { fontSize: 12, fontWeight: '900' },
  stationContentDetailBody: { fontSize: 13, fontWeight: '700', lineHeight: 21 },
  stationAlbumDetail: {
    borderRadius: spacing.cardRadius,
    gap: 12,
    padding: 12,
  },
  stationAlbumDetailMeta: { fontSize: 12, fontWeight: '800' },
  stationAlbumMediaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  stationAlbumMediaTile: {
    alignItems: 'center',
    aspectRatio: 1,
    borderRadius: 8,
    justifyContent: 'center',
    overflow: 'hidden',
    width: '31.8%',
  },
  stationAlbumMediaImage: { height: '100%', width: '100%' },
  stationAlbumEmptyDetail: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    gap: 10,
    minHeight: 120,
    justifyContent: 'center',
    padding: 12,
  },
  stationManageTextArea: {
    minHeight: 132,
    textAlignVertical: 'top',
  },
  stationManagePhotoHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  stationManageSmallButton: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    minHeight: 32,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  stationManageSmallButtonText: { fontSize: 12, fontWeight: '900' },
  stationManageMediaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  stationManageMediaItem: {
    alignItems: 'center',
    aspectRatio: 1,
    borderRadius: spacing.cardRadius,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: '31.6%',
  },
  stationManageMediaImage: { height: '100%', width: '100%' },
  stationManageMediaDelete: {
    alignItems: 'center',
    borderRadius: 999,
    bottom: 6,
    minHeight: 26,
    justifyContent: 'center',
    paddingHorizontal: 9,
    position: 'absolute',
    right: 6,
  },
  stationManageMediaDeleteText: { fontSize: 11, fontWeight: '900' },
  stationCallableAgentList: { gap: 9 },
  stationCallableAgentRow: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    flexDirection: 'row',
    gap: 10,
    minHeight: 64,
    padding: 10,
  },
  stationCallableAgentCopy: { flex: 1, gap: 4, minWidth: 0 },
  stationCallableAgentName: { fontSize: 13, fontWeight: '900' },
  stationCallableAgentDesc: { fontSize: 11, fontWeight: '700', lineHeight: 16 },
  stationCallableButton: {
    alignItems: 'center',
    borderRadius: 999,
    height: 30,
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  stationCallableButtonText: { fontSize: 12, fontWeight: '900' },
  stationModuleEmpty: {
    borderRadius: spacing.cardRadius,
    gap: 5,
    minHeight: 88,
    padding: 12,
  },
  stationModuleEmptyMeta: { fontSize: 11, fontWeight: '900' },
  stationModuleEmptyTitle: { fontSize: 13, fontWeight: '900' },
  stationModuleEmptyBody: { fontSize: 12, fontWeight: '700', lineHeight: 18 },
  stationPartnerStatusCard: {
    borderRadius: spacing.cardRadius,
    gap: 12,
    padding: 14,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 24,
  },
  stationPartnerStatusHead: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  stationPartnerStatusCopy: { flex: 1, gap: 3, minWidth: 0 },
  stationPartnerEyebrow: { fontSize: 12, fontWeight: '800' },
  stationPartnerTitle: { fontSize: 16, fontWeight: '900', lineHeight: 22 },
  stationPartnerStatusNote: { fontSize: 12, fontWeight: '700', lineHeight: 16 },
  stationPartnerAuthButton: {
    alignItems: 'center',
    borderRadius: 999,
    minHeight: 32,
    justifyContent: 'center',
    maxWidth: 112,
    paddingHorizontal: 10,
  },
  stationPartnerAuthText: { fontSize: 12, fontWeight: '900' },
  stationPartnerMetrics: { flexDirection: 'row', gap: 8 },
  stationMetricBox: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    flex: 1,
    gap: 2,
    minHeight: 58,
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  stationMetricValue: { fontSize: 18, fontWeight: '900' },
  stationMetricLabel: { fontSize: 11, fontWeight: '800' },
  stationSectionTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  stationSectionTitle: { flex: 1, fontSize: 16, fontWeight: '900' },
  stationSectionDetail: { fontSize: 12, fontWeight: '700' },
  stationSectionPill: {
    borderRadius: 999,
    fontSize: 12,
    fontWeight: '800',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  stationRecommendAgents: { gap: 10, marginTop: 4 },
  stationMarketEntry: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    flexDirection: 'row',
    gap: 11,
    minHeight: 68,
    padding: 12,
  },
  stationMarketMark: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderRadius: 16,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  stationRecommendCopy: { flex: 1, gap: 4, minWidth: 0 },
  stationRecommendTitle: { fontSize: 14, fontWeight: '900' },
  stationRecommendBody: {
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
    opacity: 0.74,
  },
  stationRadarCard: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  stationRadarMetrics: { flexDirection: 'row', gap: 8 },
  stationCard: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 12,
    padding: 14,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 16,
  },
  stationCardHeader: { alignItems: 'center', flexDirection: 'row', gap: 12 },
  stationCardTitle: { flex: 1, fontSize: 15, fontWeight: '900' },
  stationCardDetail: { fontSize: 12, fontWeight: '700' },
  stationSvgAvatarWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    top: 22,
    width: 210,
  },
  stationPlaceholder: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    gap: 10,
    justifyContent: 'center',
    minHeight: 150,
    padding: 14,
  },
  stationContentStack: { gap: 10 },
  stationContentList: { gap: 8 },
  stationContentRow: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    flexDirection: 'row',
    gap: 10,
    padding: 10,
  },
  stationContentCopy: { flex: 1, gap: 3 },
  stationContentTitle: { fontSize: 13, fontWeight: '900' },
  stationContentDetail: { fontSize: 12, lineHeight: 17 },
  stationContentMeta: { fontSize: 11, fontWeight: '800' },
  stationEmptyContentNote: {
    borderRadius: spacing.cardRadius,
    gap: 5,
    minHeight: 74,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  stationEmptyContentTitle: { fontSize: 13, fontWeight: '900' },
  stationEmptyContentBody: { fontSize: 12, lineHeight: 17 },
  miaoShowAvatarWrap: { alignItems: 'center', justifyContent: 'center' },
} as const;
