import { spacing } from '../theme';

export const stationAvatarStyles = {
  avatarSpace: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    overflow: 'hidden',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 18,
  },
  avatarSpaceCopy: { gap: 6, padding: 14 },
  avatarSpaceTitleRow: { alignItems: 'center', flexDirection: 'row', gap: 10 },
  avatarSpaceTitleCopy: { flex: 1, gap: 4 },
  avatarSpaceEyebrow: { fontSize: 12, fontWeight: '900' },
  avatarSpaceTitle: { fontSize: 20, fontWeight: '900' },
  avatarSpaceBody: { fontSize: 12, lineHeight: 18 },
  avatar3dStageWebView: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  avatar3dEmptyState: {
    alignItems: 'center',
    alignSelf: 'stretch',
    flex: 1,
    gap: 8,
    justifyContent: 'center',
    paddingHorizontal: 48,
  },
  avatar3dEmptyTitle: {
    fontSize: 15,
    fontWeight: '800',
    textAlign: 'center',
  },
  avatar3dEmptyBody: {
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center',
  },
  avatar3dRetryButton: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    minHeight: 32,
    paddingHorizontal: 8,
  },
  avatar3dRetryButtonText: {
    color: '#2012D9',
    fontSize: 12,
    fontWeight: '700',
  },
  avatar3dActionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 6,
  },
  avatar3dGenerateButton: {
    alignItems: 'center',
    borderRadius: 999,
    flexDirection: 'row',
    gap: 6,
    minHeight: 34,
    paddingHorizontal: 12,
  },
  avatar3dGenerateButtonDisabled: { opacity: 0.45 },
  avatar3dGenerateButtonText: { fontSize: 12, fontWeight: '900' },
  avatarFloatingTags: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 8,
  },
  avatarFloatingTag: {
    alignItems: 'center',
    borderRadius: 999,
    justifyContent: 'center',
    minHeight: 28,
    paddingHorizontal: 10,
    position: 'absolute',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 16,
  },
  avatarFloatingTag_0: { left: 20, top: 52 },
  avatarFloatingTag_1: { right: 18, top: 74 },
  avatarFloatingTag_2: { left: 24, top: 174 },
  avatarFloatingTag_3: { right: 28, top: 190 },
  avatarFloatingTagCallable: { minHeight: 32, paddingHorizontal: 12 },
  avatarFloatingTagText: { fontSize: 12, fontWeight: '900' },
} as const;
