import { spacing } from '../theme';

export const stationAgentStyles = {
  stationComicGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  stationComicCoverCard: {
    borderColor: '#151515',
    borderRadius: 4,
    borderWidth: 2,
    flexBasis: '48%',
    flexGrow: 1,
    gap: 6,
    minHeight: 210,
    padding: 7,
    shadowColor: '#151515',
    shadowOffset: { height: 3, width: 3 },
    shadowOpacity: 1,
    shadowRadius: 0,
  },
  stationComicCoverMuted: {
    shadowOpacity: 0,
  },
  stationComicPreview: {
    aspectRatio: 1 / 0.82,
    backgroundColor: '#151515',
    borderColor: '#151515',
    borderRadius: 6,
    borderWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 3,
    padding: 3,
  },
  stationComicTitle: { fontSize: 13, fontWeight: '900', lineHeight: 18 },
  stationComicBody: { fontSize: 11, fontWeight: '700', lineHeight: 16 },
  stationComicPromptInput: { minHeight: 96, textAlignVertical: 'top' },
  stationComicDraftStack: { gap: 12 },
  stationComicDraftCard: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 10,
    padding: 12,
  },
  stationComicDraftHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  stationComicDraftTitleWrap: { flex: 1, gap: 3, minWidth: 0 },
  stationComicDraftTitle: { fontSize: 15, fontWeight: '900' },
  stationComicDraftMeta: { fontSize: 11, fontWeight: '700' },
  stationComicDraftSummary: { fontSize: 12, lineHeight: 18 },
  stationComicFrameGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  stationComicFrameCard: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 5,
    minHeight: 118,
    padding: 10,
    width: '48%',
  },
  stationComicFrameIndex: { fontSize: 13, fontWeight: '900' },
  stationComicFrameTitle: { fontSize: 12, fontWeight: '900', lineHeight: 16 },
  stationComicFrameBody: { fontSize: 11, lineHeight: 15 },
  stationAgentMark: {
    alignItems: 'center',
    borderRadius: 999,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  stationAgentMarkText: { fontSize: 14, fontWeight: '900' },
  stationAgentLoopStack: { gap: 10 },
  stationAgentLoopStatus: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    padding: 12,
  },
  stationAgentLoopStatusCopy: { flex: 1, gap: 3, minWidth: 0 },
  stationAgentLoopEyebrow: { fontSize: 11, fontWeight: '800' },
  stationAgentLoopTitle: { fontSize: 14, fontWeight: '900', lineHeight: 19 },
  stationAgentLoopBody: { fontSize: 12, fontWeight: '700', lineHeight: 18 },
  stationAgentLoopMeta: { fontSize: 11, fontWeight: '700' },
  stationAgentLoopBadge: {
    borderRadius: 999,
    fontSize: 11,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  stationAgentLoopInput: {
    minHeight: 88,
    textAlignVertical: 'top',
  },
  stationAgentLoopActive: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 7,
    padding: 12,
  },
  stationAgentLoopCard: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 9,
    padding: 12,
  },
  stationAgentLoopCardHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  stationAgentLoopButton: {
    alignItems: 'center',
    borderRadius: 999,
    minHeight: 30,
    justifyContent: 'center',
    paddingHorizontal: 11,
  },
  stationAgentLoopButtonText: { fontSize: 12, fontWeight: '900' },
  stationAgentLoopChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  stationAgentLoopChip: {
    borderRadius: 999,
    fontSize: 11,
    fontWeight: '800',
    maxWidth: '100%',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  stationVideoPreviewStack: { gap: 8 },
  stationVideoPreviewBlock: {
    borderRadius: spacing.cardRadius,
    gap: 5,
    padding: 10,
  },
  stationVideoPreviewLine: { fontSize: 12, fontWeight: '800', lineHeight: 18 },
  stationVideoShotGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  stationVideoShotCard: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 5,
    minHeight: 86,
    padding: 9,
    width: '48%',
  },
  stationVideoShotIndex: { fontSize: 12, fontWeight: '900' },
  stationVideoShotText: { fontSize: 11, fontWeight: '800', lineHeight: 16 },
  stationAgentSection: { gap: 9 },
  stationAgentWorkbench: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  stationCapabilityGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  stationCapabilityCard: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    flexBasis: '48%',
    flexGrow: 1,
    gap: 7,
    minHeight: 112,
    padding: 10,
  },
  stationCapabilityHead: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
  },
  stationCapabilityTitle: { flex: 1, fontSize: 13, fontWeight: '900' },
  stationCapabilityBadge: {
    borderRadius: 999,
    fontSize: 11,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  stationCapabilityMeta: { fontSize: 11, fontWeight: '700', lineHeight: 16 },
  stationCapabilityResult: {
    borderTopWidth: 1,
    fontSize: 11,
    fontWeight: '800',
    lineHeight: 15,
    paddingTop: 7,
  },
  stationOwnedAgentGrid: { gap: 9 },
  stationOwnedAgentCard: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 82,
    padding: 12,
  },
  stationAgentCardDisabled: { opacity: 0.62 },
  stationOwnedAgentCopy: { flex: 1, gap: 4, minWidth: 0 },
  stationOwnedAgentName: { fontSize: 14, fontWeight: '900' },
  stationOwnedAgentDesc: { fontSize: 12, fontWeight: '700' },
  stationOwnedAgentStatus: {
    borderRadius: 999,
    fontSize: 12,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
} as const;
