import { spacing } from '../theme';

export const stationProfileStyles = {
  profileCopy: { flex: 1, gap: 7 },
  profileNameButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    flexDirection: 'row',
    gap: 8,
    maxWidth: '100%',
  },
  profileName: { fontSize: 27, fontWeight: '900' },
  profileMeta: { fontSize: 13, fontWeight: '700' },
  profileMetaStrong: {
    flexShrink: 1,
    fontSize: 13,
    fontWeight: '800',
    maxWidth: 172,
  },
  profileIconButton: {
    alignItems: 'center',
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  profilePointsPill: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 9,
    paddingVertical: 7,
  },
  profilePointsText: { fontSize: 12, fontWeight: '700' },
  profilePointsDetail: { fontSize: 12, fontWeight: '900' },
  profileRegionRow: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  profileRegionCopy: { flex: 1, flexDirection: 'row', gap: 10 },
  profileRegionTitle: { fontSize: 12, fontWeight: '700' },
  profileRegionValue: {
    flex: 1,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'right',
  },
  profileDataRow: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  profileDataTitle: { fontSize: 12, fontWeight: '700' },
  profileDataValue: {
    flex: 1,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'right',
  },
  locationHero: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 10,
    marginHorizontal: 14,
    padding: 14,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 16,
  },
  locationHeroTitle: { fontSize: 24, fontWeight: '900' },
  locationHeroDetail: { fontSize: 14, fontWeight: '800' },
  locationStatusText: { fontSize: 12, fontWeight: '700', lineHeight: 18 },
  mapPickerCard: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 10,
    marginHorizontal: 14,
    padding: 12,
  },
  mapPickerHeader: { alignItems: 'center', flexDirection: 'row', gap: 10 },
  mapPickerTitle: { flex: 1, fontSize: 15, fontWeight: '900' },
  mapPickerDetail: { fontSize: 12, fontWeight: '800' },
  mapViewport: {
    alignSelf: 'stretch',
    borderRadius: spacing.cardRadius,
    height: 320,
    overflow: 'hidden',
    position: 'relative',
    width: '100%',
  },
  mapLibreView: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  mapCrosshair: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    left: '50%',
    marginLeft: -22,
    marginTop: -22,
    position: 'absolute',
    top: '50%',
    width: 44,
  },
  mapCrosshairRing: {
    borderRadius: 999,
    borderWidth: 3,
    height: 26,
    width: 26,
  },
  mapCrosshairDot: {
    borderRadius: 999,
    height: 8,
    position: 'absolute',
    top: 18,
    width: 8,
  },
  mapCoordinateText: { fontSize: 11, fontWeight: '700', textAlign: 'center' },
  locationSection: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 9,
    marginHorizontal: 14,
    padding: 12,
  },
  locationSectionTitle: { fontSize: 12, fontWeight: '900' },
  locationCandidate: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 50,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  locationCandidateCopy: { flex: 1, gap: 3 },
  locationCandidateName: { fontSize: 14, fontWeight: '900' },
  locationCandidateDetail: { fontSize: 11, fontWeight: '700' },
  locationSelectedDot: { borderRadius: 999, height: 10, width: 10 },
  locationEmptyText: { fontSize: 12, fontWeight: '700', lineHeight: 18 },
} as const;
