import { spacing } from '../theme';

export const stationContentStyles = {
  diaryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  diaryCoverCard: {
    borderRadius: 5,
    borderWidth: 2,
    flexBasis: '48%',
    flexGrow: 1,
    gap: 7,
    minHeight: 198,
    padding: 8,
    shadowOffset: { height: 3, width: 3 },
    shadowOpacity: 1,
    shadowRadius: 0,
  },
  comicCoverPreview: {
    borderRadius: 4,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    minHeight: 122,
  },
  comicMiniPanel: {
    borderRadius: 3,
    borderWidth: 1,
    flexBasis: '47%',
    flexGrow: 1,
    minHeight: 58,
    overflow: 'hidden',
    position: 'relative',
  },
  comicMiniPanel_morning: { backgroundColor: '#fff0cc' },
  comicMiniPanel_noon: { backgroundColor: '#dff7ef' },
  comicMiniPanel_evening: { backgroundColor: '#ffd8dd' },
  comicMiniPanel_night: { backgroundColor: '#20242b' },
  comicMiniPanel_talk: { backgroundColor: '#f7efe5' },
  comicMiniPanel_cafe: { backgroundColor: '#e8f0ff' },
  comicMiniPanel_street: { backgroundColor: '#e9f4e7' },
  comicMiniPanel_sparkle: { backgroundColor: '#f8e4ff' },
  comicMiniPanel_music: { backgroundColor: '#2e2737' },
  comicMiniPanel_note: { backgroundColor: '#fff8df' },
  comicMiniPanel_sleep: { backgroundColor: '#20242b' },
  comicMiniSun: {
    borderRadius: 999,
    height: 16,
    left: 8,
    position: 'absolute',
    top: 8,
    width: 16,
  },
  comicMiniFigure: {
    borderRadius: 999,
    bottom: 8,
    height: 24,
    position: 'absolute',
    right: 10,
    width: 16,
  },
  diaryTitle: { fontSize: 13, fontWeight: '900' },
  diaryDetail: { fontSize: 11, lineHeight: 16, marginTop: 2 },
  albumGrid: { flexDirection: 'row', gap: 9 },
  albumCell: {
    borderRadius: spacing.cardRadius,
    flex: 1,
    gap: 6,
    minHeight: 128,
    overflow: 'hidden',
    padding: 7,
  },
  albumThumb: {
    alignItems: 'center',
    aspectRatio: 1,
    borderRadius: 7,
    justifyContent: 'center',
    width: '100%',
  },
  albumLabel: { fontSize: 12, fontWeight: '900' },
  albumCount: { fontSize: 11, fontWeight: '700' },
  musicList: { gap: 8 },
  musicRow: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    flexDirection: 'row',
    gap: 9,
    padding: 10,
  },
  musicIndex: { fontSize: 12, fontWeight: '900', width: 24 },
  musicCopy: { flex: 1, gap: 3 },
  musicTitle: { fontSize: 12, fontWeight: '900' },
  musicSubtitle: { fontSize: 12 },
  musicStatus: { fontSize: 11, fontWeight: '700' },
  callableAgentList: { gap: 8 },
  callableAgentRow: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    flexDirection: 'row',
    gap: 10,
    padding: 10,
  },
  callableAgentMark: {
    alignItems: 'center',
    borderRadius: 999,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  callableAgentMarkText: { color: '#ffffff', fontSize: 14, fontWeight: '900' },
  callableAgentCopy: { flex: 1, gap: 3 },
  callableAgentTitle: { fontSize: 13, fontWeight: '900' },
  callableAgentDetail: { fontSize: 12, lineHeight: 17 },
  callableAgentState: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  callableAgentStateText: { fontSize: 11, fontWeight: '900' },
  placeholderTitle: { fontSize: 17, fontWeight: '800' },
  placeholderBody: { fontSize: 12, lineHeight: 18, textAlign: 'center' },
} as const;
