export const stationPointStyles = {
  miaoPointsScreen: { flex: 1 },
  miaoPointsBackground: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 50,
  },
  miaoPointsHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    minHeight: 50,
    paddingHorizontal: 6,
  },
  miaoPointsBackButton: {
    alignItems: 'center',
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  miaoPointsBackIcon: { height: 22, width: 22 },
  miaoPointsHeaderTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 18,
    textAlign: 'center',
  },
  miaoPointsHeaderSpacer: { width: 40 },
  miaoPointsContent: { paddingBottom: 42 },
  miaoPointsHero: {
    alignSelf: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  miaoPointsHeroImage: {
    height: '100%',
    position: 'absolute',
    width: '100%',
  },
  miaoPointsHeroCopy: {
    alignSelf: 'flex-start',
    gap: 4.5,
    marginLeft: 36,
    maxWidth: '48%',
    width: 156,
  },
  miaoPointsHeroLabel: {
    color: '#000000',
    fontSize: 15,
    fontWeight: '500',
    lineHeight: 21,
  },
  miaoPointsHeroValue: {
    color: '#2012D9',
    fontSize: 30,
    fontWeight: '500',
    lineHeight: 42,
  },
  miaoPointsHeroDescription: {
    color: 'rgba(0,0,0,0.60)',
    fontSize: 12,
    lineHeight: 16.5,
  },
  miaoPointsList: { gap: 9, marginHorizontal: 12.5 },
  miaoPointRow: {
    alignItems: 'center',
    borderRadius: 4,
    elevation: 2,
    flexDirection: 'row',
    gap: 15,
    minHeight: 75,
    paddingLeft: 30,
    paddingRight: 18,
    shadowColor: '#E5E5E5',
    shadowOffset: { height: 1, width: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
  },
  miaoPointAmountBadge: {
    alignItems: 'center',
    height: 45,
    justifyContent: 'center',
    width: 45,
  },
  miaoPointAmount: {
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 21,
    maxWidth: 42,
  },
  miaoPointRowCopy: { flex: 1, gap: 5, minWidth: 0 },
  miaoPointTitle: { fontSize: 15, fontWeight: '500', lineHeight: 21 },
  miaoPointDescription: { fontSize: 12, lineHeight: 16.5 },
  miaoPointTime: {
    alignSelf: 'flex-start',
    fontSize: 12,
    lineHeight: 16.5,
    marginTop: 15.5,
    maxWidth: 92,
    textAlign: 'right',
  },
  miaoPointsState: {
    alignItems: 'center',
    gap: 5,
    justifyContent: 'center',
    marginHorizontal: 12.5,
    minHeight: 96,
    padding: 18,
  },
  miaoPointsStateTitle: {
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 21,
    textAlign: 'center',
  },
  miaoPointsStateMessage: {
    fontSize: 12,
    lineHeight: 16.5,
    textAlign: 'center',
  },
  miaoPointsEmptyRow: {
    alignItems: 'center',
    borderRadius: 4,
    elevation: 2,
    flexDirection: 'row',
    gap: 15,
    marginHorizontal: 12.5,
    minHeight: 75,
    paddingLeft: 30,
    paddingRight: 18,
    shadowColor: '#E5E5E5',
    shadowOffset: { height: 1, width: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
  },
  miaoPointsEmptyAmount: {
    color: '#2012D9',
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 21,
  },
  miaoPointsEmptyCopy: { flex: 1, gap: 5, minWidth: 0 },
  miaoPointsEmptyTitle: { fontSize: 15, fontWeight: '500', lineHeight: 21 },
  miaoPointsEmptyMessage: { fontSize: 12, lineHeight: 16.5 },
  miaoPointsRetryButton: {
    alignItems: 'center',
    borderRadius: 6,
    justifyContent: 'center',
    minHeight: 36,
    paddingHorizontal: 18,
  },
  miaoPointsRetryText: { color: '#FFFFFF', fontSize: 13, fontWeight: '600' },
} as const;
