import { spacing } from './theme';

export const stationStyles = {
  stationScrollContent: { paddingBottom: 154, paddingTop: 18 },
  stationTopContent: { gap: 14, paddingBottom: 8, paddingHorizontal: 14 },
  stationPanelWrap: { paddingHorizontal: 14, paddingTop: 16 },
  stationTopRow: { alignItems: 'flex-start', flexDirection: 'row', gap: 12 },
  profileCopy: { flex: 1, gap: 7 },
  profileNameButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    flexDirection: 'row',
    gap: 8,
    maxWidth: '100%',
  },
  profileName: { fontSize: 27, fontWeight: '900' },
  profileMeta: { fontSize: 13, fontWeight: '700' },
  profileMetaStrong: {
    flexShrink: 1,
    fontSize: 13,
    fontWeight: '800',
    maxWidth: 172,
  },
  profileIconButton: {
    alignItems: 'center',
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  profilePointsPill: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 9,
    paddingVertical: 7,
  },
  profilePointsText: { fontSize: 12, fontWeight: '700' },
  profilePointsDetail: { fontSize: 12, fontWeight: '900' },
  profileRegionRow: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  profileRegionCopy: { flex: 1, flexDirection: 'row', gap: 10 },
  profileRegionTitle: { fontSize: 12, fontWeight: '700' },
  profileRegionValue: {
    flex: 1,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'right',
  },
  stationTabHeader: {
    borderBottomWidth: 1,
    paddingBottom: 9,
    paddingHorizontal: 14,
    paddingTop: 10,
    zIndex: 20,
  },
  stationPanelStack: { gap: 12 },
  stationHomeBio: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 14,
  },
  stationHomeBioCopy: { flex: 1, gap: 6 },
  stationHomeBioTitle: { fontSize: 19, fontWeight: '900' },
  stationHomeBioBody: { fontSize: 13, lineHeight: 19 },
  stationHomeRegionButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderRadius: spacing.cardRadius,
    flexDirection: 'row',
    gap: 4,
    maxWidth: 124,
    minHeight: 34,
    paddingHorizontal: 10,
  },
  stationHomeRegionText: { flexShrink: 1, fontSize: 12, fontWeight: '900' },
  stationShortcutGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  stationShortcutTile: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    flexBasis: '48%',
    flexGrow: 1,
    gap: 8,
    minHeight: 128,
    padding: 12,
  },
  stationShortcutIcon: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  stationShortcutCopy: { gap: 3 },
  stationShortcutTitle: { fontSize: 14, fontWeight: '900' },
  stationShortcutDetail: { fontSize: 12, fontWeight: '800' },
  stationShortcutStatus: {
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 15,
    marginTop: 'auto',
  },
  stationPreviewStack: { gap: 12 },
  stationPreviewSection: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 10,
    padding: 14,
  },
  stationPreviewHeader: { alignItems: 'center', flexDirection: 'row', gap: 10 },
  stationPreviewTitle: { flex: 1, fontSize: 16, fontWeight: '900' },
  stationPreviewAction: {
    alignItems: 'center',
    flexDirection: 'row',
    minHeight: 32,
  },
  stationPreviewActionText: { fontSize: 12, fontWeight: '900' },
  stationModuleCard: {
    borderRadius: spacing.cardRadius,
    gap: 12,
    padding: 14,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 24,
  },
  stationModuleTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  stationModuleTitle: { flex: 1, fontSize: 16, fontWeight: '900' },
  stationModuleAddButton: {
    alignItems: 'center',
    borderRadius: 999,
    height: 28,
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  stationModuleAddText: { fontSize: 12, fontWeight: '900' },
  stationModuleStack: { gap: 12 },
  stationComicGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  stationComicCoverCard: {
    borderColor: '#151515',
    borderRadius: 4,
    borderWidth: 2,
    flexBasis: '48%',
    flexGrow: 1,
    gap: 6,
    minHeight: 210,
    padding: 7,
    shadowColor: '#151515',
    shadowOffset: { height: 3, width: 3 },
    shadowOpacity: 1,
    shadowRadius: 0,
  },
  stationComicCoverMuted: {
    shadowOpacity: 0,
  },
  stationComicPreview: {
    aspectRatio: 1 / 0.82,
    backgroundColor: '#151515',
    borderColor: '#151515',
    borderRadius: 6,
    borderWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 3,
    padding: 3,
  },
  stationMiniPanel: {
    borderRadius: 3,
    flexBasis: '48%',
    flexGrow: 1,
    overflow: 'hidden',
    position: 'relative',
  },
  stationMiniPanelMorning: { backgroundColor: '#f7f7f7' },
  stationMiniPanelNoon: { backgroundColor: '#e9e9e9' },
  stationMiniPanelEvening: { backgroundColor: '#dcdcdc' },
  stationMiniPanelNight: { backgroundColor: '#252525' },
  stationComicTitle: { fontSize: 13, fontWeight: '900', lineHeight: 18 },
  stationComicBody: { fontSize: 11, fontWeight: '700', lineHeight: 16 },
  stationAlbumGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  stationAlbumTile: { gap: 5, minWidth: 96, width: '31%' },
  stationAlbumCover: {
    alignItems: 'center',
    aspectRatio: 1,
    borderRadius: spacing.cardRadius,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  stationAlbumCoverSelected: { borderWidth: 2 },
  stationAlbumCoverImage: {
    height: '100%',
    width: '100%',
  },
  stationAlbumCoverText: { fontSize: 11, fontWeight: '900' },
  stationAlbumTitle: { fontSize: 13, fontWeight: '900' },
  stationAlbumCount: { fontSize: 11, fontWeight: '700' },
  stationAlbumAddPhoto: {
    alignItems: 'center',
    borderRadius: 999,
    minHeight: 28,
    justifyContent: 'center',
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  stationAlbumAddPhotoText: { fontSize: 11, fontWeight: '900' },
  stationContentDetailPanel: {
    borderRadius: spacing.cardRadius,
    gap: 10,
    padding: 12,
  },
  stationContentDetailHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  stationContentDetailCopy: { flex: 1, gap: 4, minWidth: 0 },
  stationContentDetailTitle: { flex: 1, fontSize: 16, fontWeight: '900' },
  stationContentDetailAction: { fontSize: 12, fontWeight: '900' },
  stationContentDetailBody: { fontSize: 13, fontWeight: '700', lineHeight: 21 },
  stationAlbumDetail: {
    borderRadius: spacing.cardRadius,
    gap: 12,
    padding: 12,
  },
  stationAlbumDetailMeta: { fontSize: 12, fontWeight: '800' },
  stationAlbumMediaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  stationAlbumMediaTile: {
    alignItems: 'center',
    aspectRatio: 1,
    borderRadius: 8,
    justifyContent: 'center',
    overflow: 'hidden',
    width: '31.8%',
  },
  stationAlbumMediaImage: { height: '100%', width: '100%' },
  stationAlbumEmptyDetail: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    gap: 10,
    minHeight: 120,
    justifyContent: 'center',
    padding: 12,
  },
  stationManageTextArea: {
    minHeight: 132,
    textAlignVertical: 'top',
  },
  stationComicPromptInput: { minHeight: 96, textAlignVertical: 'top' },
  stationComicDraftStack: { gap: 12 },
  stationComicDraftCard: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 10,
    padding: 12,
  },
  stationComicDraftHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  stationComicDraftTitleWrap: { flex: 1, gap: 3, minWidth: 0 },
  stationComicDraftTitle: { fontSize: 15, fontWeight: '900' },
  stationComicDraftMeta: { fontSize: 11, fontWeight: '700' },
  stationComicDraftSummary: { fontSize: 12, lineHeight: 18 },
  stationComicFrameGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  stationComicFrameCard: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 5,
    minHeight: 118,
    padding: 10,
    width: '48%',
  },
  stationComicFrameIndex: { fontSize: 13, fontWeight: '900' },
  stationComicFrameTitle: { fontSize: 12, fontWeight: '900', lineHeight: 16 },
  stationComicFrameBody: { fontSize: 11, lineHeight: 15 },
  stationManagePhotoHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  stationManageSmallButton: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    minHeight: 32,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  stationManageSmallButtonText: { fontSize: 12, fontWeight: '900' },
  stationManageMediaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  stationManageMediaItem: {
    alignItems: 'center',
    aspectRatio: 1,
    borderRadius: spacing.cardRadius,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: '31.6%',
  },
  stationManageMediaImage: { height: '100%', width: '100%' },
  stationManageMediaDelete: {
    alignItems: 'center',
    borderRadius: 999,
    bottom: 6,
    minHeight: 26,
    justifyContent: 'center',
    paddingHorizontal: 9,
    position: 'absolute',
    right: 6,
  },
  stationManageMediaDeleteText: { fontSize: 11, fontWeight: '900' },
  stationCallableAgentList: { gap: 9 },
  stationCallableAgentRow: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    flexDirection: 'row',
    gap: 10,
    minHeight: 64,
    padding: 10,
  },
  stationAgentMark: {
    alignItems: 'center',
    borderRadius: 999,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  stationAgentMarkText: { fontSize: 14, fontWeight: '900' },
  stationCallableAgentCopy: { flex: 1, gap: 4, minWidth: 0 },
  stationCallableAgentName: { fontSize: 13, fontWeight: '900' },
  stationCallableAgentDesc: { fontSize: 11, fontWeight: '700', lineHeight: 16 },
  stationCallableButton: {
    alignItems: 'center',
    borderRadius: 999,
    height: 30,
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  stationCallableButtonText: { fontSize: 12, fontWeight: '900' },
  stationModuleEmpty: {
    borderRadius: spacing.cardRadius,
    gap: 5,
    minHeight: 88,
    padding: 12,
  },
  stationModuleEmptyMeta: { fontSize: 11, fontWeight: '900' },
  stationModuleEmptyTitle: { fontSize: 13, fontWeight: '900' },
  stationModuleEmptyBody: { fontSize: 12, fontWeight: '700', lineHeight: 18 },
  stationAgentLoopStack: { gap: 10 },
  stationAgentLoopStatus: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    padding: 12,
  },
  stationAgentLoopStatusCopy: { flex: 1, gap: 3, minWidth: 0 },
  stationAgentLoopEyebrow: { fontSize: 11, fontWeight: '800' },
  stationAgentLoopTitle: { fontSize: 14, fontWeight: '900', lineHeight: 19 },
  stationAgentLoopBody: { fontSize: 12, fontWeight: '700', lineHeight: 18 },
  stationAgentLoopMeta: { fontSize: 11, fontWeight: '700' },
  stationAgentLoopBadge: {
    borderRadius: 999,
    fontSize: 11,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  stationAgentLoopInput: {
    minHeight: 88,
    textAlignVertical: 'top',
  },
  stationAgentLoopActive: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 7,
    padding: 12,
  },
  stationAgentLoopCard: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 9,
    padding: 12,
  },
  stationAgentLoopCardHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  stationAgentLoopButton: {
    alignItems: 'center',
    borderRadius: 999,
    minHeight: 30,
    justifyContent: 'center',
    paddingHorizontal: 11,
  },
  stationAgentLoopButtonText: { fontSize: 12, fontWeight: '900' },
  stationAgentLoopChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  stationAgentLoopChip: {
    borderRadius: 999,
    fontSize: 11,
    fontWeight: '800',
    maxWidth: '100%',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  stationVideoPreviewStack: { gap: 8 },
  stationVideoPreviewBlock: {
    borderRadius: spacing.cardRadius,
    gap: 5,
    padding: 10,
  },
  stationVideoPreviewLine: { fontSize: 12, fontWeight: '800', lineHeight: 18 },
  stationVideoShotGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  stationVideoShotCard: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 5,
    minHeight: 86,
    padding: 9,
    width: '48%',
  },
  stationVideoShotIndex: { fontSize: 12, fontWeight: '900' },
  stationVideoShotText: { fontSize: 11, fontWeight: '800', lineHeight: 16 },
  stationPostCard: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 10,
    padding: 12,
  },
  stationPostMeta: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  stationPostType: { fontSize: 14, fontWeight: '900' },
  stationPostTime: { fontSize: 12, fontWeight: '700' },
  stationPostTitle: { fontSize: 17, fontWeight: '900', lineHeight: 23 },
  stationPostBody: { fontSize: 14, lineHeight: 23 },
  stationPostMediaPlaceholder: {
    alignItems: 'center',
    aspectRatio: 4 / 3,
    borderRadius: spacing.cardRadius,
    justifyContent: 'center',
  },
  stationPostImage: {
    aspectRatio: 4 / 3,
    borderRadius: spacing.cardRadius,
    width: '100%',
  },
  stationPostActionRow: { flexDirection: 'row', gap: 8 },
  stationPostMediaText: { fontSize: 12, fontWeight: '900' },
  stationPostAction: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderRadius: spacing.cardRadius,
    height: 34,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  stationPostActionText: { fontSize: 13, fontWeight: '900' },
  stationPostFooter: {
    borderTopWidth: 1,
    fontSize: 12,
    fontWeight: '700',
    paddingTop: 10,
  },
  stationPartnerStatusCard: {
    borderRadius: spacing.cardRadius,
    gap: 12,
    padding: 14,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 24,
  },
  stationPartnerStatusHead: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  stationPartnerStatusCopy: { flex: 1, gap: 3, minWidth: 0 },
  stationPartnerEyebrow: { fontSize: 12, fontWeight: '800' },
  stationPartnerTitle: { fontSize: 16, fontWeight: '900', lineHeight: 22 },
  stationPartnerStatusNote: { fontSize: 12, fontWeight: '700', lineHeight: 16 },
  stationPartnerAuthButton: {
    alignItems: 'center',
    borderRadius: 999,
    minHeight: 32,
    justifyContent: 'center',
    maxWidth: 112,
    paddingHorizontal: 10,
  },
  stationPartnerAuthText: { fontSize: 12, fontWeight: '900' },
  stationPartnerMetrics: { flexDirection: 'row', gap: 8 },
  stationMetricBox: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    flex: 1,
    gap: 2,
    minHeight: 58,
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  stationMetricValue: { fontSize: 18, fontWeight: '900' },
  stationMetricLabel: { fontSize: 11, fontWeight: '800' },
  stationAgentSection: { gap: 9 },
  stationSectionTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  stationSectionTitle: { flex: 1, fontSize: 16, fontWeight: '900' },
  stationSectionDetail: { fontSize: 12, fontWeight: '700' },
  stationSectionPill: {
    borderRadius: 999,
    fontSize: 12,
    fontWeight: '800',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  stationAgentWorkbench: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  stationCapabilityGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  stationCapabilityCard: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    flexBasis: '48%',
    flexGrow: 1,
    gap: 7,
    minHeight: 112,
    padding: 10,
  },
  stationCapabilityHead: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
  },
  stationCapabilityTitle: { flex: 1, fontSize: 13, fontWeight: '900' },
  stationCapabilityBadge: {
    borderRadius: 999,
    fontSize: 11,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  stationCapabilityMeta: { fontSize: 11, fontWeight: '700', lineHeight: 16 },
  stationCapabilityResult: {
    borderTopWidth: 1,
    fontSize: 11,
    fontWeight: '800',
    lineHeight: 15,
    paddingTop: 7,
  },
  stationCapabilityRunner: { gap: 9 },
  stationCapabilityInput: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    fontSize: 13,
    lineHeight: 19,
    minHeight: 92,
    paddingHorizontal: 11,
    paddingVertical: 10,
    textAlignVertical: 'top',
  },
  stationCapabilityActions: { flexDirection: 'row', gap: 8 },
  stationCapabilityButton: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    flex: 1,
    minHeight: 38,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  stationCapabilityButtonText: { fontSize: 13, fontWeight: '900' },
  stationOwnedAgentGrid: { gap: 9 },
  stationOwnedAgentCard: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 82,
    padding: 12,
  },
  stationAgentCardDisabled: { opacity: 0.62 },
  stationOwnedAgentCopy: { flex: 1, gap: 4, minWidth: 0 },
  stationOwnedAgentName: { fontSize: 14, fontWeight: '900' },
  stationOwnedAgentDesc: { fontSize: 12, fontWeight: '700' },
  stationOwnedAgentStatus: {
    borderRadius: 999,
    fontSize: 12,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  stationRecommendAgents: { gap: 10, marginTop: 4 },
  stationMarketEntry: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    flexDirection: 'row',
    gap: 11,
    minHeight: 68,
    padding: 12,
  },
  stationMarketMark: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderRadius: 16,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  stationRecommendCopy: { flex: 1, gap: 4, minWidth: 0 },
  stationRecommendTitle: { fontSize: 14, fontWeight: '900' },
  stationRecommendBody: {
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
    opacity: 0.74,
  },
  stationRadarCard: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  stationRadarMetrics: { flexDirection: 'row', gap: 8 },
  stationCard: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 12,
    padding: 14,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 16,
  },
  stationCardHeader: { alignItems: 'center', flexDirection: 'row', gap: 12 },
  stationCardTitle: { flex: 1, fontSize: 15, fontWeight: '900' },
  stationCardDetail: { fontSize: 12, fontWeight: '700' },
  avatarSpace: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    overflow: 'hidden',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 18,
  },
  stationSvgAvatarWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    top: 22,
    width: 210,
  },
  avatarFloatingPill: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 9,
    position: 'absolute',
    shadowColor: 'rgba(0,0,0,0.16)',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 14,
    zIndex: 5,
  },
  avatarFloatingPillLeft: { left: 24, top: 72 },
  avatarFloatingPillRight: { right: 24, top: 102 },
  avatarFloatingPillBottom: { left: 32, top: 210 },
  avatarFloatingPillText: { fontSize: 12, fontWeight: '900' },
  characterShadow3d: {
    backgroundColor: 'rgba(0,0,0,0.14)',
    borderRadius: 78,
    bottom: 24,
    height: 26,
    left: '50%',
    marginLeft: -68,
    position: 'absolute',
    transform: [{ scaleX: 1.18 }],
    width: 136,
  },
  characterRig: {
    height: 268,
    left: '50%',
    marginLeft: -72,
    position: 'absolute',
    top: 25,
    width: 144,
  },
  characterBackHair: {
    borderRadius: 30,
    height: 78,
    left: '50%',
    marginLeft: -42,
    position: 'absolute',
    top: 42,
    width: 84,
  },
  characterHead: {
    backgroundColor: '#fccca0',
    borderRadius: 37,
    height: 74,
    left: '50%',
    marginLeft: -37,
    position: 'absolute',
    top: 34,
    width: 74,
    zIndex: 5,
  },
  characterHeadSide: {
    borderBottomRightRadius: 38,
    borderTopRightRadius: 38,
    bottom: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    width: 22,
  },
  characterHead3d: {
    borderColor: 'rgba(255,255,255,0.45)',
    borderLeftWidth: 2,
    shadowColor: '#000000',
    shadowOffset: { height: 9, width: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    transform: [{ rotateX: '8deg' }],
  },
  characterHair: {
    borderRadius: 13,
    height: 32,
    left: -10,
    position: 'absolute',
    top: -18,
    width: 94,
  },
  characterHair_short: { height: 30, left: -6, top: -14, width: 86 },
  characterHair_bob: {
    borderRadius: 24,
    height: 54,
    left: -8,
    top: -14,
    width: 90,
  },
  characterHair_wave: {
    borderRadius: 28,
    height: 44,
    left: -12,
    top: -18,
    transform: [{ rotate: '-5deg' }],
    width: 98,
  },
  characterHair_curly: {
    borderRadius: 999,
    height: 42,
    left: -8,
    top: -20,
    width: 90,
  },
  characterHair_undercut: {
    borderRadius: 12,
    height: 24,
    left: 8,
    top: -12,
    transform: [{ skewX: '-12deg' }],
    width: 70,
  },
  characterHairCurls: {
    borderRadius: 999,
    height: 18,
    left: 6,
    position: 'absolute',
    top: -12,
    width: 62,
  },
  characterCapBrim: {
    borderRadius: 999,
    height: 16,
    left: -4,
    position: 'absolute',
    top: 8,
    transform: [{ rotate: '-4deg' }],
    width: 84,
  },
  characterCapLetter: {
    fontSize: 13,
    fontWeight: '900',
    left: 34,
    position: 'absolute',
    top: -9,
  },
  characterEyeLeft: {
    backgroundColor: '#1a1f1c',
    borderRadius: 5,
    height: 9,
    left: 22,
    position: 'absolute',
    top: 31,
    width: 9,
  },
  characterEyeRight: {
    backgroundColor: '#1a1f1c',
    borderRadius: 5,
    height: 9,
    position: 'absolute',
    right: 22,
    top: 31,
    width: 9,
  },
  characterMouth: {
    borderColor: '#1a1f1c',
    left: 25,
    position: 'absolute',
    top: 52,
  },
  characterMouthSmile: {
    borderBottomWidth: 2,
    borderRadius: 6,
    height: 10,
    width: 24,
  },
  characterMouthCalm: { borderTopWidth: 2, height: 1, top: 56, width: 24 },
  characterMouthFocus: {
    borderTopWidth: 2,
    height: 1,
    left: 29,
    top: 56,
    width: 16,
  },
  characterAccessorySpark: {
    fontSize: 20,
    fontWeight: '900',
    position: 'absolute',
    right: -10,
    top: -12,
  },
  characterAccessoryCap: {
    borderRadius: 999,
    height: 12,
    left: 17,
    position: 'absolute',
    top: -10,
    width: 40,
  },
  characterGlasses: {
    borderColor: '#1a1f1c',
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderTopWidth: 2,
    height: 15,
    left: 18,
    position: 'absolute',
    top: 29,
    width: 38,
  },
  characterHeadphones: {
    borderRadius: 24,
    borderTopWidth: 4,
    height: 36,
    left: 10,
    position: 'absolute',
    top: 4,
    width: 54,
  },
  characterBody: {
    borderRadius: 22,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    height: 104,
    left: '50%',
    marginLeft: -45,
    position: 'absolute',
    top: 110,
    width: 90,
    zIndex: 3,
  },
  characterBodySide: {
    borderBottomRightRadius: 24,
    borderTopRightRadius: 24,
    bottom: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    width: 22,
  },
  characterArmLeft: {
    backgroundColor: '#1a1f1c',
    borderRadius: 13,
    height: 83,
    left: 23,
    position: 'absolute',
    top: 119,
    transform: [{ rotate: '-13deg' }],
    width: 22,
    zIndex: 2,
  },
  characterArmRight: {
    backgroundColor: '#1a1f1c',
    borderRadius: 13,
    height: 83,
    position: 'absolute',
    right: 23,
    top: 119,
    transform: [{ rotate: '16deg' }],
    width: 22,
    zIndex: 2,
  },
  characterHand: {
    borderRadius: 999,
    bottom: -8,
    height: 24,
    left: -1,
    position: 'absolute',
    width: 24,
  },
  characterBodyHighlight: {
    borderRadius: 18,
    height: 56,
    left: 13,
    opacity: 0.24,
    position: 'absolute',
    top: 22,
    width: 20,
  },
  characterNeck: {
    backgroundColor: '#e7ad82',
    borderRadius: 10,
    height: 22,
    left: '50%',
    marginLeft: -12,
    position: 'absolute',
    top: 96,
    width: 24,
    zIndex: 4,
  },
  characterCollar: {
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
    height: 18,
    left: '50%',
    marginLeft: -18,
    position: 'absolute',
    top: -1,
    width: 36,
  },
  characterPanel: {
    backgroundColor: '#1a1f1c',
    borderRadius: 12,
    height: 52,
    left: 31,
    position: 'absolute',
    top: 30,
    width: 28,
  },
  characterLegs: {
    flexDirection: 'row',
    gap: 15,
    left: '50%',
    marginLeft: -33,
    position: 'absolute',
    top: 201,
    zIndex: 1,
  },
  characterLegColumn: { alignItems: 'center', gap: 0 },
  characterLeg: {
    backgroundColor: '#1a1f1c',
    borderRadius: 10,
    height: 48,
    width: 25,
  },
  characterShoe: { borderRadius: 999, height: 12, marginTop: -1, width: 34 },
  avatarSpaceCopy: { gap: 6, padding: 14 },
  avatarSpaceTitleRow: { alignItems: 'center', flexDirection: 'row', gap: 10 },
  avatarSpaceTitleCopy: { flex: 1, gap: 4 },
  avatarSpaceEyebrow: { fontSize: 12, fontWeight: '900' },
  avatarSpaceTitle: { fontSize: 20, fontWeight: '900' },
  avatarSpaceBody: { fontSize: 12, lineHeight: 18 },
  avatarFloatingTags: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 8,
  },
  avatarFloatingTag: {
    alignItems: 'center',
    borderRadius: 999,
    justifyContent: 'center',
    minHeight: 28,
    paddingHorizontal: 10,
    position: 'absolute',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 16,
  },
  avatarFloatingTag_0: { left: 20, top: 52 },
  avatarFloatingTag_1: { right: 18, top: 74 },
  avatarFloatingTag_2: { left: 24, top: 174 },
  avatarFloatingTag_3: { right: 28, top: 190 },
  avatarFloatingTagCallable: { minHeight: 32, paddingHorizontal: 12 },
  avatarFloatingTagText: { fontSize: 12, fontWeight: '900' },
  avatarOotdButton: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    marginTop: 6,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  avatarOotdButtonText: { fontSize: 12, fontWeight: '900' },
  avatarRotateControls: {
    bottom: 16,
    flexDirection: 'row',
    gap: 10,
    position: 'absolute',
    right: 16,
    zIndex: 10,
  },
  avatarRotateButton: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    shadowOffset: { height: 5, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    width: 38,
  },
  profileDataRow: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  profileDataTitle: { fontSize: 12, fontWeight: '700' },
  profileDataValue: {
    flex: 1,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'right',
  },
  diaryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  diaryCoverCard: {
    borderRadius: 5,
    borderWidth: 2,
    flexBasis: '48%',
    flexGrow: 1,
    gap: 7,
    minHeight: 198,
    padding: 8,
    shadowOffset: { height: 3, width: 3 },
    shadowOpacity: 1,
    shadowRadius: 0,
  },
  comicCoverPreview: {
    borderRadius: 4,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    minHeight: 122,
  },
  comicMiniPanel: {
    borderRadius: 3,
    borderWidth: 1,
    flexBasis: '47%',
    flexGrow: 1,
    minHeight: 58,
    overflow: 'hidden',
    position: 'relative',
  },
  comicMiniPanel_morning: { backgroundColor: '#fff0cc' },
  comicMiniPanel_noon: { backgroundColor: '#dff7ef' },
  comicMiniPanel_evening: { backgroundColor: '#ffd8dd' },
  comicMiniPanel_night: { backgroundColor: '#20242b' },
  comicMiniPanel_talk: { backgroundColor: '#f7efe5' },
  comicMiniPanel_cafe: { backgroundColor: '#e8f0ff' },
  comicMiniPanel_street: { backgroundColor: '#e9f4e7' },
  comicMiniPanel_sparkle: { backgroundColor: '#f8e4ff' },
  comicMiniPanel_music: { backgroundColor: '#2e2737' },
  comicMiniPanel_note: { backgroundColor: '#fff8df' },
  comicMiniPanel_sleep: { backgroundColor: '#20242b' },
  comicMiniSun: {
    borderRadius: 999,
    height: 16,
    left: 8,
    position: 'absolute',
    top: 8,
    width: 16,
  },
  comicMiniFigure: {
    borderRadius: 999,
    bottom: 8,
    height: 24,
    position: 'absolute',
    right: 10,
    width: 16,
  },
  diaryTitle: { fontSize: 13, fontWeight: '900' },
  diaryDetail: { fontSize: 11, lineHeight: 16, marginTop: 2 },
  albumGrid: { flexDirection: 'row', gap: 9 },
  albumCell: {
    borderRadius: spacing.cardRadius,
    flex: 1,
    gap: 6,
    minHeight: 128,
    overflow: 'hidden',
    padding: 7,
  },
  albumThumb: {
    alignItems: 'center',
    aspectRatio: 1,
    borderRadius: 7,
    justifyContent: 'center',
    width: '100%',
  },
  albumLabel: { fontSize: 12, fontWeight: '900' },
  albumCount: { fontSize: 11, fontWeight: '700' },
  musicList: { gap: 8 },
  musicRow: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    flexDirection: 'row',
    gap: 9,
    padding: 10,
  },
  musicIndex: { fontSize: 12, fontWeight: '900', width: 24 },
  musicCopy: { flex: 1, gap: 3 },
  musicTitle: { fontSize: 12, fontWeight: '900' },
  musicSubtitle: { fontSize: 12 },
  musicStatus: { fontSize: 11, fontWeight: '700' },
  callableAgentList: { gap: 8 },
  callableAgentRow: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    flexDirection: 'row',
    gap: 10,
    padding: 10,
  },
  callableAgentMark: {
    alignItems: 'center',
    borderRadius: 999,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  callableAgentMarkText: { color: '#ffffff', fontSize: 14, fontWeight: '900' },
  callableAgentCopy: { flex: 1, gap: 3 },
  callableAgentTitle: { fontSize: 13, fontWeight: '900' },
  callableAgentDetail: { fontSize: 12, lineHeight: 17 },
  callableAgentState: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  callableAgentStateText: { fontSize: 11, fontWeight: '900' },
  stationFileList: { gap: 8 },
  stationFileRow: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    flexDirection: 'row',
    gap: 10,
    padding: 10,
  },
  stationFileCopy: { flex: 1, gap: 3 },
  stationFileTitle: { fontSize: 13, fontWeight: '900' },
  stationFileDetail: { fontSize: 12 },
  stationPlaceholder: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    gap: 10,
    justifyContent: 'center',
    minHeight: 150,
    padding: 14,
  },
  placeholderTitle: { fontSize: 17, fontWeight: '800' },
  placeholderBody: { fontSize: 12, lineHeight: 18, textAlign: 'center' },
  stationContentStack: { gap: 10 },
  stationContentList: { gap: 8 },
  stationContentRow: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    flexDirection: 'row',
    gap: 10,
    padding: 10,
  },
  stationContentCopy: { flex: 1, gap: 3 },
  stationContentTitle: { fontSize: 13, fontWeight: '900' },
  stationContentDetail: { fontSize: 12, lineHeight: 17 },
  stationContentMeta: { fontSize: 11, fontWeight: '800' },
  stationEmptyContentNote: {
    borderRadius: spacing.cardRadius,
    gap: 5,
    minHeight: 74,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  stationEmptyContentTitle: { fontSize: 13, fontWeight: '900' },
  stationEmptyContentBody: { fontSize: 12, lineHeight: 17 },
  miaoShowAvatarWrap: { alignItems: 'center', justifyContent: 'center' },
  locationHero: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 10,
    marginHorizontal: 14,
    padding: 14,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 16,
  },
  locationHeroTitle: { fontSize: 24, fontWeight: '900' },
  locationHeroDetail: { fontSize: 14, fontWeight: '800' },
  locationStatusText: { fontSize: 12, fontWeight: '700', lineHeight: 18 },
  mapPickerCard: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 10,
    marginHorizontal: 14,
    padding: 12,
  },
  mapPickerHeader: { alignItems: 'center', flexDirection: 'row', gap: 10 },
  mapPickerTitle: { flex: 1, fontSize: 15, fontWeight: '900' },
  mapPickerDetail: { fontSize: 12, fontWeight: '800' },
  mapViewport: {
    alignSelf: 'stretch',
    borderRadius: spacing.cardRadius,
    height: 320,
    overflow: 'hidden',
    position: 'relative',
    width: '100%',
  },
  mapLibreView: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  mapCrosshair: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    left: '50%',
    marginLeft: -22,
    marginTop: -22,
    position: 'absolute',
    top: '50%',
    width: 44,
  },
  mapCrosshairRing: {
    borderRadius: 999,
    borderWidth: 3,
    height: 26,
    width: 26,
  },
  mapCrosshairDot: {
    borderRadius: 999,
    height: 8,
    position: 'absolute',
    top: 18,
    width: 8,
  },
  mapCoordinateText: { fontSize: 11, fontWeight: '700', textAlign: 'center' },
  locationSection: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 9,
    marginHorizontal: 14,
    padding: 12,
  },
  locationSectionTitle: { fontSize: 12, fontWeight: '900' },
  locationCandidate: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 50,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  locationCandidateCopy: { flex: 1, gap: 3 },
  locationCandidateName: { fontSize: 14, fontWeight: '900' },
  locationCandidateDetail: { fontSize: 11, fontWeight: '700' },
  locationSelectedDot: { borderRadius: 999, height: 10, width: 10 },
  locationEmptyText: { fontSize: 12, fontWeight: '700', lineHeight: 18 },
} as const;
