import { StyleSheet } from 'react-native';

import { spacing } from './theme';
import { messageStyles } from './messageStyles';
import { stationStyles } from './stationStyles';

export const styles = StyleSheet.create({
  ...messageStyles,
  ...stationStyles,
  safeArea: { flex: 1 },
  launchOverlay: {
    alignItems: 'center',
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    padding: 28,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 100,
  },
  launchCopy: { gap: 10 },
  launchLine: {
    fontSize: 25,
    fontWeight: '900',
    lineHeight: 32,
    textAlign: 'center',
  },
  launchLineEmphasis: { fontSize: 28, lineHeight: 36 },
  launchCaption: { fontSize: 13, marginBottom: 14, marginTop: 24 },
  launchDots: { flexDirection: 'row', gap: 7 },
  launchDot: { borderRadius: 999, height: 7, width: 7 },
  authScreen: { flex: 1 },
  authTopNoticeWrap: {
    alignItems: 'center',
    left: 0,
    paddingHorizontal: 18,
    position: 'absolute',
    right: 0,
    top: 18,
    zIndex: 20,
  },
  authTopNotice: {
    borderRadius: 999,
    maxWidth: '100%',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  authTopNoticeText: { color: '#ffffff', fontSize: 13, fontWeight: '900' },
  authContent: { flex: 1, gap: 28, justifyContent: 'center', padding: 24 },
  authHero: { gap: 12 },
  authTitle: { fontSize: 48, fontWeight: '900' },
  authSubtitle: { fontSize: 19, fontWeight: '600', lineHeight: 27 },
  authFields: { gap: 10 },
  authSubmitContent: { alignItems: 'center', flexDirection: 'row', gap: 8 },
  authLargeInput: {
    borderRadius: 12,
    borderWidth: 1,
    fontSize: 15,
    minHeight: 50,
    paddingHorizontal: 13,
    paddingVertical: 12,
  },
  authSubmit: {
    alignItems: 'center',
    borderRadius: 12,
    justifyContent: 'center',
    minHeight: 50,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  authSubmitText: { color: '#ffffff', fontSize: 17, fontWeight: '900' },
  authValidationSlot: { minHeight: 18, justifyContent: 'center' },
  authValidationText: { fontSize: 12, fontWeight: '800', lineHeight: 16 },
  authFieldErrorHidden: { color: 'transparent' },
  authModeRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    paddingTop: 2,
  },
  authModeText: { fontSize: 13, fontWeight: '700' },
  authModeAction: { fontSize: 13, fontWeight: '900' },
  authNote: {
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 18,
    textAlign: 'center',
  },
  disabledButton: { opacity: 0.56 },
  pointerEventsBoxNone: { pointerEvents: 'box-none' },
  pointerEventsNone: { pointerEvents: 'none' },
  restoreScreen: {
    flex: 1,
    justifyContent: 'center',
    padding: 24,
  },
  restorePanel: { gap: 14 },
  restoreTitle: { fontSize: 26, fontWeight: '900', lineHeight: 34 },
  restoreMessage: { fontSize: 15, fontWeight: '700', lineHeight: 23 },
  restorePrimaryButton: {
    alignItems: 'center',
    borderRadius: 12,
    justifyContent: 'center',
    marginTop: 8,
    minHeight: 50,
    paddingHorizontal: 16,
  },
  restorePrimaryText: { color: '#ffffff', fontSize: 16, fontWeight: '900' },
  restoreSecondaryButton: {
    alignItems: 'center',
    minHeight: 40,
    justifyContent: 'center',
  },
  restoreSecondaryText: { fontSize: 14, fontWeight: '800' },
  shell: { flex: 1 },
  screen: { flex: 1 },
  topBar: {
    alignItems: 'center',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 10,
    paddingBottom: 10,
    paddingHorizontal: spacing.pageX,
    paddingTop: 14,
  },
  iconButton: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  iconButtonBorderless: { borderWidth: 0 },
  segment: {
    alignSelf: 'stretch',
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 4,
    padding: 4,
  },
  segmentFill: { flex: 1 },
  segmentButton: {
    alignItems: 'center',
    borderRadius: 7,
    borderWidth: 1,
    borderColor: 'transparent',
    flex: 1,
    minHeight: 34,
    justifyContent: 'center',
  },
  segmentLabelRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    paddingVertical: 8,
  },
  segmentText: {
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
  },
  segmentBadge: {
    alignItems: 'center',
    borderRadius: 999,
    justifyContent: 'center',
    minWidth: 18,
    paddingHorizontal: 5,
    paddingVertical: 2,
  },
  segmentBadgeText: { color: '#ffffff', fontSize: 10, fontWeight: '900' },
  avatar: {
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 48,
  },
  avatarSmall: { height: 36, width: 36 },
  avatarAccent: {
    fontSize: 13,
    fontWeight: '900',
    position: 'absolute',
    right: 5,
    top: 2,
  },
  avatarMiniCharacter: {
    alignItems: 'center',
    height: 70,
    justifyContent: 'center',
    marginTop: 18,
    width: 70,
  },
  avatarMiniCharacterSmall: { height: 54, marginTop: 14, width: 54 },
  avatarMiniFace: {
    alignItems: 'center',
    borderColor: 'rgba(255,255,255,0.55)',
    borderRadius: 999,
    borderWidth: 1,
    height: 31,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 31,
  },
  avatarMiniFaceSmall: { height: 24, width: 24 },
  avatarMiniHair: {
    borderRadius: 10,
    height: 13,
    left: -3,
    position: 'absolute',
    top: -3,
    width: 37,
  },
  avatarMiniHair_short: { height: 12, left: -2, top: -2, width: 35 },
  avatarMiniHair_bob: { height: 18, left: -4, top: -2, width: 39 },
  avatarMiniHair_wave: {
    height: 15,
    left: -5,
    top: -4,
    transform: [{ rotate: '-8deg' }],
    width: 42,
  },
  avatarMiniHair_curly: {
    borderRadius: 999,
    height: 17,
    left: -3,
    top: -5,
    width: 38,
  },
  avatarMiniHair_undercut: {
    height: 10,
    left: 4,
    top: -1,
    transform: [{ skewX: '-12deg' }],
    width: 25,
  },
  avatarMiniEyes: { flexDirection: 'row', gap: 7, marginTop: 8 },
  avatarMiniEye: {
    backgroundColor: '#1a1f1c',
    borderRadius: 999,
    height: 3.5,
    width: 3.5,
  },
  avatarMiniMouth: { borderColor: '#1a1f1c', marginTop: 4 },
  avatarMiniMouthSmile: {
    borderBottomWidth: 1.5,
    borderRadius: 5,
    height: 5,
    width: 12,
  },
  avatarMiniMouthCalm: { borderTopWidth: 1.5, height: 1, width: 12 },
  avatarMiniMouthFocus: { borderTopWidth: 1.5, height: 1, width: 8 },
  avatarMiniGlasses: {
    borderColor: '#1a1f1c',
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderTopWidth: 1,
    height: 7,
    left: 7,
    position: 'absolute',
    top: 13,
    width: 17,
  },
  avatarMiniCap: {
    borderRadius: 999,
    height: 5,
    left: 6,
    position: 'absolute',
    top: 1,
    width: 19,
  },
  avatarMiniHeadphones: {
    borderRadius: 12,
    borderTopWidth: 2,
    height: 17,
    left: 5,
    position: 'absolute',
    top: 6,
    width: 21,
  },
  avatarText: {
    bottom: 2,
    fontSize: 9,
    fontWeight: '900',
    position: 'absolute',
    right: 4,
  },
  avatarTextSmall: { bottom: 1, fontSize: 7, right: 3 },
  agentAvatar: {
    alignItems: 'center',
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 48,
  },
  agentAvatarSmall: { height: 36, width: 36 },
  agentAvatarCore: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1.5,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  agentAvatarCoreSmall: { height: 25, width: 25 },
  agentAvatarMark: { fontSize: 18, fontWeight: '900' },
  agentAvatarMarkSmall: { fontSize: 13 },
  agentAvatarSignal: {
    borderRadius: 999,
    height: 8,
    position: 'absolute',
    right: 5,
    top: 5,
    width: 8,
  },
  agentAvatarSignalSmall: { height: 6, right: 4, top: 4, width: 6 },
  chatScreen: { flex: 1 },
  chatSwipeSurface: { flex: 1 },
  chatHeader: {
    alignItems: 'center',
    borderBottomWidth: 0.5,
    flexDirection: 'row',
    minHeight: 62,
    paddingBottom: 8,
    paddingHorizontal: 14,
    paddingTop: 8,
  },
  chatBackButton: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 0,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  chatBackIcon: {height: 22, width: 22},
  chatHeaderTitleWrap: {
    alignItems: 'center',
    flex: 1,
    gap: 2,
    justifyContent: 'center',
  },
  chatHeaderTitle: {
    fontSize: 17,
    fontWeight: '900',
    textAlign: 'center',
  },
  chatHeaderSubtitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
    justifyContent: 'center',
  },
  chatHeaderSubtitle: { fontSize: 11, fontWeight: '700', textAlign: 'center' },
  chatHeaderSpacer: { width: 42 },
  chatHeaderActionButton: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 0,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  header: {
    alignItems: 'center',
    borderBottomWidth: 1,
    flexDirection: 'row',
    minHeight: 54,
    paddingHorizontal: 12,
  },
  backButton: {
    alignItems: 'center',
    borderRadius: 999,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  headerTitle: {
    flex: 1,
    fontSize: 17,
    fontWeight: '900',
    textAlign: 'center',
  },
  headerSpacer: { width: 38 },
  presenceAnchor: { position: 'relative' },
  presencePill: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    flexShrink: 0,
    gap: 4,
    minHeight: 24,
    paddingHorizontal: 7,
  },
  presenceDot: { borderRadius: 999, height: 7, width: 7 },
  presencePillText: { fontSize: 11, fontWeight: '900' },
  presenceFloatingMenu: {
    borderRadius: 10,
    borderWidth: 1,
    elevation: 32,
    gap: 2,
    minWidth: 126,
    padding: 5,
    position: 'absolute',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 18,
    zIndex: 900,
  },
  presenceOverlayDismiss: {
    bottom: 0,
    elevation: 31,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 890,
  },
  presenceMenuItem: {
    alignItems: 'center',
    borderRadius: 7,
    flexDirection: 'row',
    gap: 8,
    minHeight: 32,
    paddingHorizontal: 8,
  },
  presenceMenuText: { fontSize: 13, fontWeight: '900' },
  aiIdActions: { flexDirection: 'row', gap: 2 },
  aiIdRow: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    flexDirection: 'row',
    gap: 4,
    maxWidth: '100%',
  },
  statsRow: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    flexDirection: 'row',
    height: 64,
  },
  statDivider: { height: 46, width: 1 },
  statCell: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  statValue: { fontSize: 17, fontWeight: '900' },
  statLabel: { fontSize: 12, marginTop: 4 },
  panel: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 8,
    padding: 16,
  },
  panelTitle: { fontSize: 17, fontWeight: '900' },
  panelBody: { fontSize: 14, lineHeight: 21 },
  siteBuilderHero: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 10,
    marginHorizontal: 18,
    minHeight: 196,
    padding: 18,
  },
  siteBuilderHeroIcon: {
    alignItems: 'center',
    borderRadius: 999,
    height: 58,
    justifyContent: 'center',
    width: 58,
  },
  siteBuilderTitle: { fontSize: 24, fontWeight: '900', textAlign: 'center' },
  siteBuilderBody: { fontSize: 14, lineHeight: 21, textAlign: 'center' },
  siteBuilderCapabilities: { gap: 12, paddingHorizontal: 18 },
  siteBuilderCapabilityRow: {
    alignItems: 'flex-start',
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 14,
  },
  siteBuilderCapabilityIcon: {
    alignItems: 'center',
    borderRadius: 10,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  siteBuilderCapabilityCopy: { flex: 1, gap: 5 },
  siteBuilderCapabilityTitle: { fontSize: 16, fontWeight: '900' },
  siteBuilderCapabilitySubtitle: { fontSize: 13, lineHeight: 19 },
  searchScreen: { flex: 1 },
  searchPageHeader: {
    alignItems: 'center',
    borderBottomWidth: 0.5,
    flexDirection: 'row',
    gap: 12,
    minHeight: 58,
    paddingBottom: 10,
    paddingHorizontal: 22,
    paddingTop: 10,
  },
  searchBackButton: {
    alignItems: 'center',
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  searchBackIcon: {height: 22, width: 22},
  searchField: {
    alignItems: 'center',
    borderRadius: 5,
    borderWidth: 0,
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 38,
    paddingHorizontal: 12,
  },
  searchInput: {flex: 1, fontSize: 14, minHeight: 38, paddingVertical: 8},
  searchContent: {flex: 1},
  searchListViewport: {flex: 1},
  searchResults: {
    gap: 30,
    paddingBottom: 36,
    paddingHorizontal: 22,
    paddingTop: 14,
  },
  searchSection: {gap: 14},
  searchSectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  searchSectionTitle: {color: '#000000', fontSize: 15, fontWeight: '700'},
  searchSectionAction: {fontSize: 12, fontWeight: '600'},
  searchHistoryList: {flexDirection: 'row', flexWrap: 'wrap', gap: 9},
  searchHistoryCollapsed: {overflow: 'hidden'},
  searchChip: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#F4F6FF',
    borderRadius: 999,
    borderColor: '#DBE2FF',
    borderWidth: 1,
    flexDirection: 'row',
    gap: 4,
    maxWidth: '48%',
    minHeight: 32,
    overflow: 'hidden',
    paddingLeft: 12,
    paddingRight: 6,
    paddingVertical: 6,
  },
  searchChipLabelButton: {flexShrink: 1, minWidth: 0},
  searchChipText: {
    color: 'rgba(0,0,0,0.6)',
    flexShrink: 1,
    fontSize: 12,
    fontWeight: '500',
  },
  searchChipDelete: {
    alignItems: 'center',
    height: 18,
    justifyContent: 'center',
    width: 18,
  },
  searchHistoryToggle: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    flexDirection: 'row',
    gap: 3,
    minHeight: 24,
  },
  searchHistoryToggleText: {
    color: '#2012D9',
    fontSize: 12,
    fontWeight: '600',
  },
  searchDirectoryList: {gap: 12, width: '100%'},
  searchDirectoryGroup: {gap: 3},
  searchDirectoryInitial: {
    color: 'rgba(0,0,0,0.6)',
    fontSize: 12,
    fontWeight: '500',
  },
  searchRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    minHeight: 86,
    paddingVertical: 14,
  },
  searchRowDivider: {borderBottomWidth: 2},
  searchRowCopy: {flex: 1, gap: 5},
  searchRowTitle: {fontSize: 15, fontWeight: '900'},
  searchRowBody: {fontSize: 12, lineHeight: 18},
  searchEmpty: {fontSize: 13, lineHeight: 20},
  searchBottomFade: {
    flexBasis: '9%',
    flexGrow: 0,
    flexShrink: 0,
    width: '100%',
  },
  searchBottomSafeArea: {backgroundColor: '#F1EFFA'},
  publicProfileContent: { gap: 14, paddingBottom: 28 },
  publicProfileHero: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    marginHorizontal: 14,
    padding: 14,
  },
  publicProfileCopy: { flex: 1, gap: 5 },
  publicProfileName: { fontSize: 20, fontWeight: '900' },
  publicProfileMeta: { fontSize: 12, fontWeight: '700' },
  publicProfileBio: { fontSize: 13, lineHeight: 19 },
  publicProfileStats: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 14,
  },
  publicProfileStat: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    flex: 1,
    gap: 4,
    paddingVertical: 12,
  },
  publicProfileStatValue: { fontSize: 20, fontWeight: '900' },
  publicProfileStatTitle: { fontSize: 12, fontWeight: '800' },
  publicProfileActions: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 14,
  },
  publicProfileAction: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    flex: 1,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: 12,
  },
  publicProfileActionOutlined: { borderWidth: 1 },
  publicProfileActionContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 22,
  },
  publicProfileActionText: { fontSize: 15, fontWeight: '900' },
  loadingState: {
    flex: 1,
  },
  loadingStateBody: {
    alignItems: 'center',
    flex: 1,
    gap: 12,
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  loadingStateText: { fontSize: 13, fontWeight: '800', textAlign: 'center' },
  relationshipStack: { gap: 12 },
  relationshipSection: { gap: 8 },
  relationshipSectionTitle: { fontSize: 12, fontWeight: '900' },
  relationshipRow: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    flexDirection: 'row',
    gap: 10,
    padding: 10,
  },
  relationshipProfileButton: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 10,
  },
  relationshipChatButton: {
    alignItems: 'center',
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  relationshipCopy: { flex: 1, gap: 3 },
  relationshipName: { fontSize: 14, fontWeight: '900' },
  relationshipMeta: { fontSize: 12, fontWeight: '700' },
  relationshipEmpty: { fontSize: 12, lineHeight: 18 },
  floatingMiao: {
    alignItems: 'center',
    borderRadius: 999,
    bottom: spacing.bottomBarMinHeight + 22,
    height: 31,
    justifyContent: 'center',
    left: '50%',
    marginLeft: -15.5,
    position: 'absolute',
    width: 31,
    zIndex: 3,
  },
  floatingMiaoText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
    includeFontPadding: false,
    lineHeight: 14,
    textAlign: 'center',
    textAlignVertical: 'center',
  },
  bottomBar: {
    borderTopWidth: 1,
    flexDirection: 'row',
    flexShrink: 0,
    minHeight: spacing.bottomBarMinHeight,
    paddingVertical: 8,
  },
  tabButton: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    gap: 5,
  },
  tabIcon: { height: 20, width: 20 },
  tabTitle: { fontSize: 12, fontWeight: '700' },
  avatarStagePressable: { height: 318, overflow: 'hidden' },
  avatarStage: {
    alignItems: 'center',
    height: 318,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
  },
  avatarStageStation: { height: 238 },
  avatarStageRotationOverlay: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 12,
  },
  avatarStageHorizon: {
    backgroundColor: 'rgba(26,31,28,0.12)',
    height: 1,
    left: 34,
    position: 'absolute',
    right: 34,
    top: 232,
  },
  avatarStageHorizonHome: { top: 216 },
  avatarStageHorizonStation: { top: 190 },
  avatarStagePanel: {
    borderRadius: 18,
    borderWidth: 1,
    bottom: 28,
    left: 54,
    position: 'absolute',
    right: 54,
    top: 28,
  },
  avatarMusicNote: {
    fontSize: 30,
    fontWeight: '900',
    position: 'absolute',
    zIndex: 4,
  },
  avatarMusicNoteOne: {
    right: 116,
    top: 92,
    transform: [{ rotate: '-13deg' }],
  },
  avatarMusicNoteTwo: { left: 116, top: 130, transform: [{ rotate: '16deg' }] },
  settingsContent: { gap: 14, paddingBottom: 28 },
  settingsHeader: { gap: 14, paddingHorizontal: 14, paddingTop: 2 },
  settingsDismissButton: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  settingsLargeTitle: { fontSize: 34, fontWeight: '900' },
  settingsAccountCard: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    marginHorizontal: 14,
    padding: 14,
  },
  settingsAccountCopy: { flex: 1, gap: 4 },
  settingsAccountName: { fontSize: 17, fontWeight: '900' },
  settingsAccountRole: { fontSize: 12 },
  settingsSegmentRow: { gap: 8 },
  settingsSegmentTitle: { fontSize: 12, fontWeight: '700' },
  settingsInputWrap: { gap: 7 },
  settingsInput: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    fontSize: 14,
    minHeight: 42,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  settingsInputMultiline: { minHeight: 74, textAlignVertical: 'top' },
  settingsActionRow: { flexDirection: 'row', gap: 10 },
  settingsActionButton: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: 12,
  },
  settingsActionButtonText: { fontSize: 14, fontWeight: '900' },
  settingsRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  settingsRowTitleWrap: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 8,
  },
  settingsRowTitle: { fontSize: 15, fontWeight: '700' },
  settingsRowValue: { fontSize: 14, fontWeight: '700' },
  settingHint: { fontSize: 12, lineHeight: 18 },
  logoutRow: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    flexDirection: 'row',
    gap: 10,
    padding: 12,
  },
  logoutIconBox: {
    alignItems: 'center',
    borderRadius: spacing.cardRadius,
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  logoutCopy: { flex: 1, gap: 2 },
  logoutTitle: { fontSize: 15, fontWeight: '900' },
  logoutHint: { fontSize: 12 },
  toastWrap: {
    alignItems: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 72,
    zIndex: 50,
  },
  toast: {
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  toastText: { fontSize: 12, fontWeight: '900' },
  qrModalOverlay: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  qrSheetBackdrop: { flex: 1 },
  qrScreen: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderTopWidth: 1,
    bottom: 0,
    left: 0,
    maxHeight: '54%',
    minHeight: 370,
    position: 'absolute',
    right: 0,
  },
  qrHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    paddingBottom: 10,
    paddingHorizontal: 20,
    paddingTop: 18,
  },
  qrCircleButton: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  qrTitle: { flex: 1, fontSize: 20, fontWeight: '900' },
  qrTimer: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  qrTimerText: { fontSize: 12, fontWeight: '900' },
  qrRefreshButton: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  qrContent: {
    alignItems: 'center',
    gap: 14,
    paddingBottom: 24,
    paddingHorizontal: 20,
    paddingTop: 8,
  },
  qrDiyFrame: {
    alignItems: 'center',
    height: 224,
    justifyContent: 'center',
    position: 'relative',
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 18,
    width: 224,
  },
  qrTape: {
    borderRadius: 4,
    height: 22,
    opacity: 0.78,
    position: 'absolute',
    top: -3,
    width: 96,
    zIndex: 2,
  },
  qrDiyCard: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1.5,
    height: 212,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 212,
  },
  qrInnerPatch: {
    alignItems: 'center',
    borderRadius: 12,
    justifyContent: 'center',
    padding: 7,
    zIndex: 1,
  },
  qrCornerMark: {
    borderLeftWidth: 3,
    borderTopWidth: 3,
    left: 13,
    position: 'absolute',
    top: 13,
  },
  qrStamp: {
    borderRadius: 999,
    height: 12,
    opacity: 0.25,
    position: 'absolute',
    width: 12,
  },
  qrHandMark: {
    bottom: 9,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0,
    position: 'absolute',
    right: 12,
  },
  qrAiIdPill: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  qrAiIdText: { fontSize: 12, fontWeight: '900' },
  settingGroup: {
    borderRadius: spacing.cardRadius,
    borderWidth: 1,
    gap: 10,
    marginHorizontal: 14,
    padding: 14,
  },
  settingTitle: { fontSize: 12, fontWeight: '900' },
  authInput: {
    borderRadius: 8,
    fontSize: 15,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  primaryButton: {
    alignItems: 'center',
    borderRadius: 8,
    minHeight: 44,
    justifyContent: 'center',
  },
  primaryButtonText: { color: '#ffffff', fontSize: 15, fontWeight: '900' },
  secondaryButton: {
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 42,
  },
  secondaryButtonText: { fontSize: 15, fontWeight: '900' },
  signedInText: { fontSize: 13, lineHeight: 19 },
  errorText: { fontSize: 13, fontWeight: '700' },
});
