# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'MiaoxunRN' do
  $MLRN_SPM_SPEC = {
    url: "https://github.com/maplibre/maplibre-gl-native-distribution",
    requirement: {
      kind: "exactVersion",
      version: "6.26.0"
    },
    product_name: "MapLibre"
  }

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    $MLRN.post_install(installer)

    maplibre_package_url = $MLRN_SPM_SPEC[:url]
    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.user_project.native_targets.each do |user_target|
        user_target.package_product_dependencies.dup.each do |dependency|
          next unless dependency.product_name == $MLRN_SPM_SPEC[:product_name]
          next if dependency.package&.repositoryURL == maplibre_package_url

          user_target.package_product_dependencies.delete(dependency)
          dependency.remove_from_project
        end
      end

      aggregate_target.user_project.root_object.package_references.dup.each do |package|
        next unless package.respond_to?(:repositoryURL)
        next unless package.repositoryURL&.include?("maplibre-gl-native-distribution")
        next if package.repositoryURL == maplibre_package_url

        aggregate_target.user_project.root_object.package_references.delete(package)
        package.remove_from_project
      end

      aggregate_target.user_project.save
    end
  end
end
