import { StyleSheet } from 'react-native';

export const retrievalStyles = StyleSheet.create({
  screen: { flex: 1 },
  content: { padding: 18, gap: 20, paddingBottom: 44 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  back: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
  },
  headerTitle: { flex: 1, fontSize: 20, fontWeight: '700' },
  title: { fontSize: 24, lineHeight: 32, fontWeight: '700' },
  sectionTitle: { fontSize: 17, fontWeight: '600' },
  subtitle: { fontSize: 14, lineHeight: 22 },
  caption: { fontSize: 12, lineHeight: 18 },
  card: { borderRadius: 20, padding: 18, gap: 14, borderWidth: 1 },
  row: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  wrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  column: { gap: 8 },
  flex: { flex: 1 },
  button: {
    minHeight: 48,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 18,
    borderRadius: 14,
  },
  buttonText: { fontSize: 15, fontWeight: '600' },
  white: { color: '#FFFFFF' },
  disabled: { opacity: 0.45 },
  input: {
    minHeight: 88,
    borderRadius: 14,
    padding: 14,
    fontSize: 16,
    lineHeight: 24,
    textAlignVertical: 'top',
    borderWidth: 1,
  },
  chip: {
    borderWidth: 1,
    borderRadius: 18,
    minHeight: 38,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  consent: { alignItems: 'flex-start', gap: 10, paddingVertical: 6 },
  checkbox: {
    borderWidth: 1,
    width: 22,
    height: 22,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  result: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 12,
    gap: 12,
    flexDirection: 'row',
  },
  thumbnail: { width: 84, height: 96, borderRadius: 10 },
  video: {
    width: 84,
    height: 96,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  tag: { borderRadius: 5, paddingHorizontal: 6, paddingVertical: 3 },
  resultText: { fontSize: 14, lineHeight: 21, fontWeight: '500' },
  inlineAction: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
});
